- name: include postgresql configuration tasks
  include: postgresql.yml
  become: yes
  tags: postgresql

- name: include rsnapshot/backup configuration tasks
  include: backups.yml
  become: yes
  tags:
    - postgresql
    - backup

- name: include netdata configuration tasks
  include: netdata.yml
  become: yes
  tags:
    - postgresql
    - monitoring
    - netdata
  when:
    - ansible_local.netdata.ansible_managed is defined
    - ansible_local.netdata.ansible_managed | bool

- name: include ansible-facts configuration tasks
  include: fact.yml
  become: yes
  tags: postgresql

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: postgresql

##### UTILITIES #####
# These tasks are tagged 'never' and will never run unless one of their tags is explicitly passed on the command line
- name: include pgmetrics tasks
  include: utils-pgmetrics.yml
  become: yes
  tags:
    - never
    - utils-pgmetrics
