- include: postgresql.yml
  become: yes
  tags: postgresql

- include: monitoring.yml
  become: yes
  tags:
    - postgresql
    - monitoring
  when: "'nodiscc.xsrv.monitoring' in role_names"

- include: fact.yml
  become: yes
  tags: postgresql

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: postgresql

##### UTILITIES #####
# These tasks are tagged 'never' and will never run unless one of their tags is explicitly passed on the command line

- include: utils-pgmetrics.yml
  become: yes
  tags:
    - never
    - utils-pgmetrics
