---

- name: install postgresql
  apt:
    state: present
    package:
      - postgresql
      - postgresql-client

- name: create directory for postgresql dumps
  file:
    state: directory
    path: /var/backups/postgresql/
    owner: root
    group: postgres
    mode: 0770
