- name: setup firewalld rules for openldap
  ansible.posix.firewalld:
    zone: "{{ item[1].zone }}"
    service: "{{ item[0] }}"
    state: "{{ item[1].state }}"
    permanent: yes
    immediate: yes
  with_nested:
    - ['ldap', 'ldaps']
    - "{{ openldap_firewalld_zones }}"
