- include: checks.yml
  tags:
    - openldap
    - checks

- include: ssl-selfsigned.yml
  become: yes
  tags:
    - apache
    - ssl
    - openldap

- include: openldap.yml
  become: yes
  tags: openldap

- include: populate.yml
  become: yes
  tags: openldap

- include: backups.yml
  become: yes
  tags:
    - openldap
    - backup

- include: ldap-account-manager.yml
  become: yes
  when: openldap_setup_lam|bool
  tags:
    - openldap
    - ldap-account-manager

- include: self-service-password.yml
  become: yes
  when: openldap_setup_ssp|bool
  tags:
    - openldap
    - self-service-password

- include: monitoring.yml
  become: yes
  tags:
    - openldap
    - monitoring
    - ldap-account-manager
    - self-service-password
  when: "'nodiscc.xsrv.monitoring' in role_names"

- include: fact.yml
  become: yes
  tags: openldap

- include: firewalld.yml
  become: yes
  tags:
    - openldap
    - firewall
  when:
    - ansible_local.firewalld.ansible_managed is defined
    - ansible_local.firewalld.ansible_managed|bool

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: openldap
