- name: include variable checks tasks
  include: checks.yml
  tags:
    - openldap
    - checks

- name: include openldap configuration tasks
  include: openldap.yml
  become: yes
  tags: openldap

- name: include LDAP database population tasks
  include: populate.yml
  become: yes
  tags: openldap

- name: include rsnapshot/backup configuration tasks
  include: backups.yml
  become: yes
  tags:
    - openldap
    - backup

- name: include self-signed certificates configuration tasks
  include: ssl-selfsigned.yml
  become: yes
  tags:
    - ssl
    - openldap
    - openldap-ssl

- name: include ldap-account-manager configuration tasks
  include: ldap-account-manager.yml
  become: yes
  tags:
    - openldap
    - ldap-account-manager
  when: openldap_setup_lam | bool

- name: include self-service password configuration tasks
  include: self-service-password.yml
  become: yes
  tags:
    - openldap
    - self-service-password
  when: openldap_setup_ssp | bool

- name: include netdata configuration tasks
  include: netdata.yml
  become: yes
  tags:
    - openldap
    - monitoring
    - netdata
    - ldap-account-manager
    - self-service-password
  when:
    - ansible_local.netdata.ansible_managed is defined
    - ansible_local.netdata.ansible_managed | bool

- name: include firewalld configuration tasks
  include: firewalld.yml
  become: yes
  tags:
    - openldap
    - firewall
  when:
    - ansible_local.firewalld.ansible_managed is defined
    - ansible_local.firewalld.ansible_managed | bool

- name: include ansible facts configuration tasks
  include: fact.yml
  become: yes
  tags: openldap

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: openldap
