- name: restart apache
  service:
    name: apache2
    state: restarted
    enabled: yes
  become: yes
  when: apache_enable_service|bool

- name: reload apache
  service:
    name: apache2
    state: reloaded
    enabled: yes
  become: yes
  when: apache_enable_service|bool

- name: restart php-fpm
  service:
    name: php7.4-fpm
    state: restarted
    enabled: yes
  become: yes

- name: update ansible facts
  setup:
