# @tag netdata - setup netdata monitoring system
# @tag netdata-config - copy netdata configuration files

galaxy_info:
  role_name: monitoring_netdata
  author: "nodiscc <nodiscc@gmail.com>"
  description: "Lightweight real-time monitoring and alerting system"
  license: GPL-3.0
  min_ansible_version: 2.8
  platforms:
    - name: Debian
      versions:
        - 10
        - 11
  galaxy_tags:
    - system
    - performance
    - monitoring
    - alerting
    - health
    - graphs
    - charts
dependencies:
  - nodiscc.xsrv.handlers
