# @tag tt_rss - setup tt-rss feed reader

galaxy_info:
  role_name: tt_rss
  author: "nodiscc <nodiscc@gmail.com>"
  description: "Tiny Tiny RSS web-based news feed reader"
  license: GPL-3.0
  min_ansible_version: 2.12
  platforms:
    - name: Debian
      versions:
        - 10
        - 11
  galaxy_tags:
    - web
    - rss
    - atom
    - news
    - feed
    - reader
dependencies:
  - nodiscc.xsrv.handlers
  - nodiscc.xsrv.apache
  # - nodiscc.xsrv.common
  # - nodiscc.xsrv.backup
  # - nodiscc.xsrv.postgresql
