---

##### NEXTCLOUD #####

# Nextcloud admin username/password
nextcloud_user: "{{ vault_nextcloud_user }}" # CHANGEME
nextcloud_password: "{{ vault_nextcloud_password }}" # CHANGEME

# Fully Qualified Domain Name for the nextcloud instance
# nextcloud_fqdn: "cloud.CHANGEME.org"
# Nextcloud installation directory (must be under a valid documentroot)
nextcloud_install_dir: "/var/www/{{ nextcloud_fqdn }}"
# full public URL of your tt-rss installation (update this if you changed the install location to a subdirectory)
nextcloud_full_url: "https://{{ nextcloud_fqdn }}/"

# mode for SSL/TLS certificates for the nextcloud webserver virtualhost
# letsencrypt: acquire a certificate from Let's Encrypt (nextcloud_fqdn must be piblicly resolvable, port tcp/80 must be reachable from the Internet)
# selfsigned: generate a self-signed certificate (will generate warning in bowsers and clients)
nextcloud_https_mode: selfsigned

# nextcloud data storage directory
nextcloud_data_dir: "/var/nextcloud/data"

# nextcloud adminstrator e-mail address
nextcloud_admin_email: "admin@{{ nextcloud_fqdn }}"

# nextcloud database type (mysql/pgsql)
nextcloud_db_type: "pgsql"
# nextcloud database host
# use /var/run/postgresql and unset the password to use postgresql local peer authentication
nextcloud_db_host: "localhost"
# nextcloud database name
nextcloud_db_name: "nextcloud"
# nextcloud database table prefix
nextcloud_db_table_prefix: "oc_"
# nextcloud database user
nextcloud_db_user: "nextcloud"
# nextcloud database password
nextcloud_db_password: "{{ vault_nextcloud_db_password }}" # CHANGEME

# nextcloud version to install
nextcloud_version: "19.0.0"

# Nextcloud applications to enable or disable
# state: enable/disable
# app: nextcloud app name
nextcloud_apps:
  - { state: "disable", app: "encryption" }
  - { state: "disable", app: "files_antivirus" }
  - { state: "disable", app: "files_versions" }
  - { state: "disable", app: "news" }
  - { state: "disable", app: "user_external" }
  - { state: "disable", app: "recommendations" }
  - { state: "enable", app: "activity" }
  - { state: "enable", app: "calendar" }
  - { state: "enable", app: "comments" }
  - { state: "enable", app: "contacts" }
  - { state: "enable", app: "dav" }
  - { state: "enable", app: "federatedfilesharing" }
  - { state: "enable", app: "federation" }
  - { state: "enable", app: "files" }
  - { state: "enable", app: "files_external" }
  - { state: "enable", app: "files_pdfviewer" }
  - { state: "enable", app: "files_sharing" }
  - { state: "enable", app: "files_trashbin" }
  - { state: "enable", app: "files_videoplayer" }
  - { state: "enable", app: "firstrunwizard" }
  - { state: "enable", app: "photos" }
  - { state: "enable", app: "music" }
  - { state: "enable", app: "notifications" }
  - { state: "enable", app: "systemtags" }
  - { state: "enable", app: "tasks" }
  - { state: "enable", app: "updatenotification" }
  - { state: "enable", app: "user_ldap" }
  - { state: "enable", app: "notes" }
#  - { state: "enable", app: "documents" } #TODO requires download
#  - { state: "enable", app: "templateeditor" } #TODO requires download
