- name: check samba configuration
  become: yes
  command: testparm -s
  listen: reload samba

- name: reload samba
  become: yes
  service:
    name: "{{ item }}"
    state: reloaded
  with_items:
    - smbd
    - nmbd

- name: update ansible facts
  setup:

- name: restart nslcd
  become: yes
  service:
    name: nslcd
    state: restarted
    enabled: yes

- name: restart nscd
  become: yes
  service:
    name: nscd
    state: restarted
    enabled: yes
