##### JELLYFIN INSTALLATION #####

- name: install jellyfin requirements
  apt:
    state: present
    package:
      - apt-transport-https

- name: import jellyfin gpg signing key
  apt_key:
    state: present
    url: https://repo.jellyfin.org/debian/jellyfin_team.gpg.key

- name: add jellyfin APT repository
  apt_repository:
    state: present
    repo: deb [arch=amd64] https://repo.jellyfin.org/debian {{ ansible_distribution_release | lower }} main
    filename: jellyfin

- name: install jellyfin
  apt:
    state: present
    package: jellyfin
  notify: display jellyfin first run message

##### MEDIA DIRECTORIES #####

- name: create default media directories
  file:
    path: "/var/lib/jellyfin/{{ item }}"
    state: directory
    owner: jellyfin
    group: jellyfin
    mode: 02770
  with_items:
    - media
    - media/movies
    - media/music
    - media/shows
    - media/books
    - media/photos
    - media/musicvideos
    - media/mixedcontent

- name: create symlink from home directory to jellyfin media directory
  file:
    state: link
    dest: "{{ ansible_env.HOME }}/MEDIA"
    src: "/var/lib/jellyfin/media/"

# required to allow jellyfin group to write in subdirectories
- name: set permissions on jellyfin data directory
  file:
    path: /var/lib/jellyfin
    owner: jellyfin
    group: jellyfin
    mode: 0770

- name: allow ansible user to read/write jellyfin data files
  user:
    name: "{{ ansible_user }}"
    groups: jellyfin
    append: yes

##### JELLYFIN SAMBA SHARE #####

- name: create mountpoint for jellyfin samba share
  file:
    state: directory
    path: /var/lib/jellyfin/sambashare
    owner: root
    group: sambausers
    mode: 0755
  when: "'nodiscc.xsrv.samba' in role_names and jellyfin_samba_share_enabled|bool"

- name: mount jellyfin samba share to jellyfin directory
  mount:
    path: /var/lib/jellyfin/sambashare
    src: /var/lib/samba/shares/jellyfin
    opts: bind
    state: mounted
    fstype: none
  when: "'nodiscc.xsrv.samba' in role_names and jellyfin_samba_share_enabled|bool"

- name: create jellyfin samba share subdirectories
  file:
    path: /var/lib/samba/shares/jellyfin/{{ item }}
    state: directory
    owner: jellyfin
    group: sambausers
    mode: 02775
  with_items:
    - movies
    - music
    - shows
    - books
    - photos
    - musicvideos
    - mixedcontent
  when: "'nodiscc.xsrv.samba' in role_names and jellyfin_samba_share_enabled|bool"

- name: run all notified handlers
  meta: flush_handlers

###### FAIL2BAN #####

- name: copy jellyfin fail2ban jail config
  template:
    src: etc_fail2ban_jail.d_jellyfin.conf.j2
    dest: /etc/fail2ban/jail.d/jellyfin.conf
    mode: 0644
  tags: fail2ban
  notify: reload fail2ban
  when: "'nodiscc.xsrv.common' in role_names"

- name: copy fail2ban jellyfin-auth filter
  template:
    src: etc_fail2ban_filter.d_jellyfin-auth.conf.j2
    dest: /etc/fail2ban/filter.d/jellyfin-auth.conf
    mode: 0644
  tags: fail2ban
  notify: reload fail2ban
  when: "'nodiscc.xsrv.common' in role_names"

##### SERVICE #####

- name: enable jellyfin service
  service: name=jellyfin state=started enabled=yes
  when: jellyfin_enable_service|bool
  tags: services

- name: disable jellyfin service
  service: name=jellyfin state=stopped enabled=no
  when: not jellyfin_enable_service|bool
  tags: services
