##### JELLYFIN INSTALLATION #####

- name: install jellyfin requirements
  apt:
    state: present
    package:
      - apt-transport-https

- name: import jellyfin gpg signing key
  apt_key:
    state: present
    url: https://repo.jellyfin.org/debian/jellyfin_team.gpg.key

- name: add jellyfin APT repository
  apt_repository:
    state: present
    repo: deb [arch=amd64] https://repo.jellyfin.org/debian {{ ansible_distribution_release | lower }} main
    filename: jellyfin

- name: install jellyfin
  apt:
    state: present
    package: jellyfin
  notify: display jellyfin first run message

##### MEDIA DIRECTORIES #####

- name: create default media directories
  file:
    path: "/var/lib/jellyfin/{{ item }}"
    state: directory
    owner: jellyfin
    group: jellyfin
    mode: 02770
  with_items:
    - media
    - media/movies
    - media/music
    - media/shows
    - media/books
    - media/photos
    - media/musicvideos
    - media/mixedcontent

- name: create symlink from home directory to jellyfin media directory
  file:
    state: link
    dest: "{{ ansible_env.HOME }}/MEDIA"
    src: "/var/lib/jellyfin/media/"

# required to allow jellyfin group to write in subdirectories
- name: set permissions on jellyfin data directory
  file:
    path: /var/lib/jellyfin
    owner: jellyfin
    group: jellyfin
    mode: 0770

- name: allow ansible user to read/write jellyfin data files
  user:
    name: "{{ ansible_user }}"
    groups: jellyfin
    append: yes

- name: allow jellyfin to read/write transmission downloads directory
  user:
    name: jellyfin
    group: debian-transmission
    append: yes
  when:
    - ansible_local.transmission.ansible_managed is defined
    - ansible_local.transmission.ansible_managed|bool

##### SERVICE #####

- name: start/stop/enable/disable jellyfin service
  service:
    name: jellyfin
    state: "{{ 'started' if jellyfin_enable_service else 'stopped' }}"
    enabled: "{{ 'yes' if jellyfin_enable_service else 'no' }}"
  tags: services
