- include: checks.yml
  become: yes
  tags:
    - jellyfin
    - checks

- include: jellyfin.yml
  become: yes
  tags: jellyfin

- include: ssl-selfsigned.yml
  become: yes
  tags: jellyfin
  when: jellyfin_https_mode == 'selfsigned'

- include: apache.yml
  become: yes
  tags:
    - jellyfin
    - apache

- include: backups.yml
  become: yes
  tags:
    - jellyfin
    - backup

- include: monitoring.yml
  become: yes
  tags:
    - jellyfin
    - monitoring
  when: "'nodiscc.xsrv.monitoring' in role_names"
