- name: add netdata httpcheck for jellyfin
  template:
    src: etc_netdata_go.d_httpcheck.conf.d_jellyfin.conf.j2
    dest: "/etc/netdata/go.d/httpcheck.conf.d/jellyfin.conf"
    owner: root
    group: netdata
    mode: 0640
  notify: assemble netdata configuration

- name: ensure netdata configuration is applied (flush handlers)
  meta: flush_handlers
