---

galaxy_info:
  role_name: gitea
  author: nodiscc
  description: Gitea self-hosted Git service/software forge
  license: GPL-3.0
  min_ansible_version: 2.8
  platforms:
    - name: Debian
      versions:
        - 10
  galaxy_tags:
    - git
    - project
    - development
    - issues
    - wiki
    - vcs
    - web
