---

##### PACKAGES ###################

- name: configure APT to install apache and modules from buster-backports
  template:
    src: etc_apt_preferences.d_99-apache2-buster-backports.j2
    dest: /etc/apt/preferences.d/99-apache2-buster-backports
    mode: 0644
  register: apache_apt_pinning

# refresh APT cache after updating APT preferences
- name: update apt cache # noqa 503
  become: yes
  apt:
    update_cache: yes
  when: apache_apt_pinning.changed

- name: install apache/php packages
  apt:
    state: present
    package:
      - apache2
      - libapache2-mod-evasive
      - libapache2-mod-php
      - libapache2-mod-md
      - php-apcu
      - php

- name: install libapache2-mod-md from buster-backports
  apt:
    state: present
    package:
      - libapache2-mod-md
    default_release: buster-backports


##### APACHE MODULES/CONFIGURATON #####

- name: copy apache2/php configuration
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items:
    - { src: 'etc_apache2_conf-available_security.conf.j2', dest: '/etc/apache2/conf-available/security.conf' }
    - { src: 'etc_apache2_conf-available_logging.conf.j2', dest: '/etc/apache2/conf-available/logging.conf' }
    - { src: 'etc_apache2_conf-available_ssl-common.conf.j2', dest: '/etc/apache2/conf-available/ssl-common.conf' }
    - { src: 'etc_apache2_ports.conf.j2', dest: '/etc/apache2/ports.conf' }
    - { src: 'etc_php_7.3_apache2_conf.d_30-hide-header.ini.j2', dest: '/etc/php/7.3/apache2/conf.d/30-hide-header.ini' }
  notify: reload apache

- name: disable unnecessary apache modules
  command: a2dismod {{ item }}
  args:
    removes: /etc/apache2/mods-enabled/cgi.load
  with_items:
    - 'cgi'
  notify: restart apache

- name: enable apache modules
  command: a2enmod {{ item }}
  args:
    creates: "/etc/apache2/mods-enabled/{{ item }}.load"
  with_items:
    - 'auth_basic'
    - 'headers'
    - 'rewrite'
    - 'php7.3'
    - 'md'
    - 'ssl'
  notify: restart apache

- name: enable apache configuration snippets
  command: a2enconf {{ item }}
  args:
    creates: "/etc/apache2/conf-enabled/{{ item }}.conf"
  with_items:
    - 'security'
    - 'logging'
    - 'ssl-common'
  notify: reload apache

- include: apache-mod-evasive.yml


##### APACHE VIRTUALHOSTS #####

- name: create documentroot directories for virtualhosts
  file:
    state: directory
    path: "{{ item.documentroot }}"
    owner: root
    group: www-data
    mode: 0750
  with_items: "{{ apache_virtualhosts }}"

- name: copy robots.txt
  template:
    src: var_www_virtualhost_robots.txt.j2
    dest: "{{ item.documentroot }}/robots.txt"
    owner: root
    group: www-data
    mode: 0640
  with_items: "{{ apache_virtualhosts }}"

- name: copy apache sites config
  template:
    src: etc_apache2_sites-available_000-sites.conf.j2
    dest: /etc/apache2/sites-available/000-sites.conf
    mode: 0644
  notify: reload apache

- name: disable default apache sites
  command: a2dissite {{ item }}
  args:
    removes: /etc/apache2/sites-enabled/{{ item }}.conf
  with_items:
    - 000-default
    - default-ssl
  notify: restart apache

- name: remove default virtualhost index.html page
  file:
    path: /var/www/html/index.html
    state: absent

- name: enable apache sites
  command: a2ensite 000-sites
  args:
    creates: /etc/apache2/sites-enabled/000-sites.conf
  notify: reload apache

- name: remove virtualhost configuration from previous versions of the role
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/apache2/sites-enabled/sites.conf
    - /etc/apache2/sites-available/sites.conf
  notify: reload apache

##### SERVICE #####

- name: enable apache service
  service: name=apache2 state=started enabled=yes
  when: apache_enable_service|bool
  tags: services

- name: disable apache service
  service: name=apache2 state=stopped enabled=no
  when: not apache_enable_service|bool
  tags: services
