- include: checks.yml
  tags:
    - apache
    - lamp

- include: ssl-selfsigned.yml
  become: yes
  tags:
    - apache
    - lamp
    - certificates
    - ssl

- include: apache.yml
  become: yes
  tags:
    - apache
    - lamp

- include: monitoring.yml
  become: yes
  tags:
    - apache
    - lamp
    - monitoring
  when:
    - '"nodiscc.xsrv.monitoring" in role_names'

- name: restart apache to apply configuration changes
  meta: flush_handlers
  tags:
    - apache
    - lamp
