- include: checks.yml
  tags:
    - apache
    - lamp
    - checks

- include: ssl-selfsigned.yml
  become: yes
  tags:
    - apache
    - lamp
    - certificates
    - ssl

- include: apache.yml
  become: yes
  tags:
    - apache
    - lamp

- include: fail2ban.yml
  become: yes
  tags:
    - apache
    - lamp
    - fail2ban
  when:
    - "'nodiscc.xsrv.common' in role_name"
    - setup_fail2ban|bool

- include: monitoring.yml
  become: yes
  tags:
    - apache
    - lamp
    - monitoring
  when:
    - '"nodiscc.xsrv.monitoring" in role_names'

- include: fact.yml
  become: yes
  tags: apache

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: apache
