- include: checks.yml
  tags:
    - apache
    - checks

- include: ssl-selfsigned.yml
  become: yes
  tags:
    - apache
    - ssl

- include: apache.yml
  become: yes
  tags:
    - apache

- include: fail2ban.yml
  become: yes
  tags:
    - apache
    - fail2ban
  when:
    - "'nodiscc.xsrv.common' in role_name"
    - setup_fail2ban|bool

- include: monitoring.yml
  become: yes
  tags:
    - apache
    - monitoring
  when:
    - '"nodiscc.xsrv.monitoring" in role_names'

- include: fact.yml
  become: yes
  tags: apache

- include: firewalld.yml
  become: yes
  tags:
    - apache
    - firewall
  when:
    - ansible_local.firewalld.ansible_managed is defined
    - ansible_local.firewalld.ansible_managed|bool

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags:
    - apache
    - monitoring
    - fail2ban
