---

- include: apache-ssl-selfsigned.yml
  become: yes
  tags:
    - apache
    - lamp
    - certificates
    - ssl

- include: apache.yml
  become: yes
  tags:
    - apache
    - lamp

- name: restart apache to apply configuration changes
  meta: flush_handlers
  tags:
    - apache
    - lamp
