- include: checks.yml
  tags:
    - apache
    - lamp

- include: apache-ssl-selfsigned.yml
  become: yes
  tags:
    - apache
    - lamp
    - certificates
    - ssl

- include: apache.yml
  become: yes
  tags:
    - apache
    - lamp

- include: rsyslog.yml
  become: yes
  tags:
    - apache
    - lamp
    - rsyslog
  when:
    - '"nodiscc.xsrv.monitoring" in role_names'
    - setup_rsyslog|bool

- name: restart apache to apply configuration changes
  meta: flush_handlers
  tags:
    - apache
    - lamp
