##### APACHE MONITORING #####

- name: forward all www-data cron jobs mail to root
  lineinfile:
    path: /etc/aliases
    state: present
    create: yes
    regexp: "^www-data"
    line: "www-data: root"
    owner: root
    group: root
    mode: 0644

- name: configure rsyslog to aggregate apache access/error and php-fpm logs to syslog
  template:
    src: etc_rsyslog.d_{{ item }}.conf.j2
    dest: /etc/rsyslog.d/{{ item }}.conf
    owner: root
    group: root
    mode: 0644
  with_items:
    - apache
    - php-fpm
  notify: restart rsyslog
  when: setup_rsyslog|bool

- name: install netdata process check for apache
  template:
    src: etc_netdata_health.d_processes.conf.d_apache.conf.j2
    dest: /etc/netdata/health.d/processes.conf.d/apache.conf
    owner: root
    group: netdata
    mode: 0640
  notify: assemble netdata configuration
