image: python:3

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"

cache:
  paths:
    - "$CI_PROJECT_DIR/pip-cache"

test:
  before_script:
    - apt-get update -qy
    - apt-get install -y shellcheck python3-venv
    - export LC_ALL=C.UTF-8
    - export LANG=C.UTF-8
  script:
    - make tests
