image: python:3

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"

cache:
  paths:
    - "$CI_PROJECT_DIR/pip-cache"

test:
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "C.UTF-8"
  script:
    - make install_deps tests
  interruptible: true
