---

- src: git+https://gitlab.com/nodiscc/ansible-xsrv-common
  version: "1.7.0"
  name: common

- src: git+https://gitlab.com/nodiscc/ansible-xsrv-backup
  version: "1.5.0"
  name: backup

- src: git+https://gitlab.com/nodiscc/ansible-xsrv-monitoring
  version: "1.3.0"
  name: monitoring

- src: git+https://gitlab.com/nodiscc/ansible-xsrv-lamp
  version: "1.6.0"
  name: lamp

- src: git+https://gitlab.com/nodiscc/ansible-xsrv-nextcloud
  version: "1.2.0"
  name: nextcloud

- src: git+https://gitlab.com/nodiscc/ansible-xsrv-tt-rss
  version: "1.0"
  name: tt-rss

- src: git+https://gitlab.com/nodiscc/ansible-xsrv-gitea
  version: "1.0.0"
  name: gitea
