---

- src: git+https://gitlab.com/nodiscc/ansible-xsrv-common
  version: "1.4"
  name: common

- src: git+https://gitlab.com/nodiscc/ansible-xsrv-backup
  version: "1.3.0"
  name: backup

- src: git+https://gitlab.com/nodiscc/ansible-xsrv-monitoring
  version: "1.2"
  name: monitoring

- src: git+https://gitlab.com/nodiscc/ansible-xsrv-lamp
  version: "1.4"
  name: lamp

- src: git+https://gitlab.com/nodiscc/ansible-xsrv-nextcloud
  version: "1.0.4"
  name: nextcloud
