---

- src: git+https://gitlab.com/nodiscc/ansible-xsrv-common
  version: "1.2.1"
  name: common

- src: git+https://gitlab.com/nodiscc/ansible-xsrv-backup
  version: "1.0.1"
  name: backup

- src: git+https://gitlab.com/nodiscc/ansible-xsrv-monitoring
  version: "1.1"
  name: monitoring

- src: git+https://gitlab.com/nodiscc/ansible-xsrv-lamp
  version: "1.1.1"
  name: lamp

- src: git+https://gitlab.com/nodiscc/ansible-xsrv-nextcloud
  version: "1.0.1"
  name: nextcloud
