### configuration variables for my.example.org (plaintext)
##### COMMON #####
# ansible_ssh_port: 22

##### GITEA #####
# https://gitlab.com/nodiscc/xsrv/-/blob/master/roles/gitea/defaults/main.yml
gitea_fqdn: "git.CHANGEME.org"

##### HOMEPAGE #####
# https://gitlab.com/nodiscc/xsrv/-/blob/master/roles/homepage/defaults/main.yml
homepage_fqdn: "www.CHANGEME.org"

##### JELLYFIN #####
# https://gitlab.com/nodiscc/xsrv/-/blob/master/roles/jellyfin/defaults/main.yml
jellyfin_fqdn: "media.CHANGEME.org"

##### NEXTCLOUD #####
# https://gitlab.com/nodiscc/xsrv/-/blob/master/roles/nextcloud/defaults/main.yml
nextcloud_fqdn: "cloud.CHANGEME.org"

##### SHAARLI #####
# sehttps://gitlab.com/nodiscc/xsrv/-/blob/master/roles/shaarli/defaults/main.yml
shaarli_fqdn: "links.CHANGEME.org"

##### TRANSMISSION #####
# https://gitlab.com/nodiscc/xsrv/-/blob/master/roles/transmission/defaults/main.yml
transmission_fqdn: "torrent.CHANGEME.org"

##### TT-RSS #####
# https://gitlab.com/nodiscc/xsrv/-/blob/master/roles/tt_rss/defaults/main.yml
tt_rss_fqdn: "rss.CHANGEME.org"

##### ROCKETCHAT #####
# shttps://gitlab.com/nodiscc/xsrv/-/blob/master/roles/rocketchat/defaults/main.yml
rocketchat_fqdn: "chat.CHANGEME.org"

#### OPENLDAP ####
# https://gitlab.com/nodiscc/xsrv/-/blob/master/roles/openldap/defaults/main.yml
openldap_fqdn: "ldap.CHANGEME.org"
openldap_domain: "CHANGEME.org"
openldap_organization: "CHANGEME"
openldap_base_dn: "dc=CHANGEME,dc=org"

##### GRAYLOG #####
graylog_fqdn: "logs.CHANGEME.org"

#### GOTTY ####
gotty_auth_username: "CHANGEME"
gotty_auth_password: "CHANGEME"
gotty_run_username: "CHANGEME"


##### FIREWALL/FAIL2BAN #####
# https://gitlab.com/nodiscc/xsrv/-/blob/master/roles/common/defaults/main.yml
firehol_alias_lan: "10.0.0.0/8,192.168.0.0/16,172.16.0.0/12"

firehol_networks:
  - name: "global"
    src: "any" # traffic to/from any IP address
    interface: "any" # traffic to/from any network interface
    policy: "RETURN" # pass packets to next chain when no rules match
    allow_input: # incoming traffic
      - { name: "ssh", src: "any" } # ssh from anywhere
      - { name: "netdata", src: "{{ firehol_alias_lan }}" } # monitoring dashboard
      - { name: "http", src: "any" } # web server
      - { name: "https", src: "any" } # web server
      # - { name: "samba", src: "{{ firehol_alias_lan }}" } # samba file sharing
      # - { name: "mumble", src: "{{ firehol_alias_lan }}" } # mumble voip server
      # - { name: "ping", src: "{{ firehol_alias_lan }}" } # incoming ICMP pings
      # - { name: "pulseaudio", src: "{{ firehol_alias_lan }}" } # pulseaudio sound server
      # - { name: "mdns", src: "any" } # avahi/zeroconf/MDNS/DNS-SD/uPnP, requires src: any
      # - { name: "multicast", src: "any" } # avahi/zeroconf/MDNS/DNS-SD/uPnP, requires src=any
      # - { name: "sshcustom", src: "any" } # SSH server on custom port
      # - { name: "transmission", src: "any" } # incoming bittorrent/transmission peer connections
      # - { name: "rtc", src: "any", } # jitsi meet audio/video conferencing
      # - { name: "ldap", src: "{{ firehol_alias_lan }}", } # LDAP (plain/insecure) from LAN
      # - { name: "ldaps", src: "{{ firehol_alias_lan }}" } # LDAP (SSL/secure) from LAN
      # - { name: "graylogtcp5140", src: "{{ firehol_alias_lan }}" } # graylog syslog input (TCP/SSL)
    allow_output: # outgoing connections
      - { name: "dns", dst: "any" } # DNS queries to anywhere
      - { name: "ntp", dst: "any" } # time/date synchronization
      - { name: "dhcp", dst: "{{ firehol_alias_lan }}" } # DHCP requests on LAN
      - { name: "http", dst: "any" } # outgoing HTTP requests
      - { name: "https", dst: "any" } # outgoing HTTPS requests
      - { name: "ping", dst: "any" } # outgoing ICMP pings
      - { name: "submission", dst: "any" } # outgoing mail/port 587
      - { name: "smtps", dst: "any" } # outgoing mail/port 465
      # - { name: "samba", dst: "{{ firehol_alias_lan }}" } # samba file sharing
      # - { name: "imaps", dst: "any" } # nextcloud mail
      # - { name: "ssh", dst: "any" } # ssh/git access to anywhere
      # - { name: "all", dst: "any" } # allow ALL outgoing connections (required for bittorrent/transmission)
