##### JELLYFIN MEDIA SERVER #####

# fully qualified domain name of the jellyfin instance
# jellyfin_fqdn: "media.CHANGEME.org"

# HTTPS and SSL/TLS certificate mode for the jellyfin webserver virtualhost
#   letsencrypt: acquire a certificate from letsencrypt.org
#   selfsigned: generate a self-signed certificate (will generate warning in bowsers and clients)
jellyfin_https_mode: selfsigned

# yes/no: start/stop the jellyfin webserver, enable/disable it on boot
jellyfin_enable_service: yes

# if the samba role is enabled, enable a jellyfin samba share (upload media files there)
jellyfin_samba_share_enabled: yes
# lists of users allowed to read/write to the jellyfin samba share (use @groupname for groups)
jellyfin_samba_share_allow_write_users: []
jellyfin_samba_share_allow_read_users: []
