##### JELLYFIN MEDIA SERVER #####

# fully qualified domain name of the jellyfin instance
# jellyfin_fqdn: "media.CHANGEME.org"

# HTTPS and SSL/TLS certificate mode for the jellyfin webserver virtualhost
#   letsencrypt: acquire a certificate from letsencrypt.org
#   selfsigned: generate a self-signed certificate (will generate warning in bowsers and clients)
jellyfin_https_mode: selfsigned

# yes/no: start/stop the jellyfin webserver, enable/disable it on boot
jellyfin_enable_service: yes
