galaxy_info:
  role_name: shaarli
  author: "nodiscc <nodiscc@gmail.com>"
  description: "Bookmarking & link sharing web application"
  license: GPL-3.0
  min_ansible_version: 2.8
  platforms:
    - name: Debian
      versions:
        - 9
        - 10
  galaxy_tags:
    - server
    - bookmarks
    - links
    - microblog
    - sharing
    - notes
dependencies:
  - nodiscc.xsrv.handlers
  - nodiscc.xsrv.apache
