---

##### GITEA SELF-HOSTED GIT SERVICE #####

# fully qualified domain name of the gitea instance
# gitea_fqdn: "git.CHANGEME.org"

# username/password/e-mail address for the gitea admin user
gitea_admin_username: "{{ vault_gitea_admin_username }}"
gitea_admin_password: "{{ vault_gitea_admin_password }}"
gitea_admin_email: "{{ vault_gitea_admin_email }}"

# gitea database settings
gitea_db_type: "postgres" # postgres/mysql
gitea_db_name: "gitea"
gitea_db_user: "gitea"
gitea_db_host: "/run/postgresql/" # /run/postgresql/ for a local postgresql database
gitea_db_password: "{{ vault_gitea_db_password }}"
gitea_db_port: 5432 # usually 5432 for PostgreSQL, 3306 for MySQL

# gitea version to install - https://github.com/go-gitea/gitea/releases.atom; remove leading v
gitea_version: '1.12.3'
# 106 character token used for internal API calls authentication
gitea_internal_token: " {{ vault_gitea_internal_token }}"
# 64 character global secret key
gitea_secret_key: "{{ vault_gitea_secret_key }}"
# 32 character OAuth2 JWT secret
gitea_oauth2_jwt_secret: "{{ vault_gitea_oauth2_jwt_secret }}"
# 44 character LFS JWT secret
gitea_lfs_jwt_secret: "{{ vault_gitea_lfs_jwt_secret }}"
# home directory for the gitea user
gitea_user_home: /var/lib/gitea
# gitea base URL under the domain name (eg change. it to /gitea to serve from https://git.CHANGEME.org/gitea)
gitea_base_url: "/"
# start/stop the gitea service, enable/disable it on boot (yes/no)
gitea_enable_service: yes

# HTTPS and SSL/TLS certificate mode for the gitea webserver virtualhost
#   letsencrypt: acquire a certificate from Let's Encrypt (tt_rss_fqdn must be piblicly resolvable, port tcp/80 must be reachable from the Internet)
#   selfsigned: generate a self-signed certificate (will generate warning in bowsers and clients)
gitea_https_mode: selfsigned


### Gitea settings ###

# Default visibility setting when creating a new repository (last/private/public)
gitea_default_private: "private"
# force every new repository to be private (true/false - QUOTED)
gitea_force_private: "false"
# User must sign in to view anything (true/false - QUOTED)
gitea_require_signin: "true"
# Disallow registration, only allow admins to create accounts (true/false - QUOTED)
gitea_disable_registration: "true"
# Whether the email of the user should be shown in the Explore Users page (true/false - QUOTED)
gitea_show_user_email: "false"
# disable all third-party/external services/CDNs (true/false - QUOTED)
gitea_offline_mode: "true"
# disable third-party gravatar service (true/false - QUOTED)
gitea_disable_gravatar: "true"
# global limit of repositories per user, applied at creation time. -1 means no limit
gitea_user_repo_limit: -1
# enable/disable gitea REST API (true/false - QUOTED)
gitea_enable_api: "false"
# The minimum password length for new Users
gitea_min_password_length: 10

# enable outgoing mail (yes/no)
gitea_mailer_enabled: no
# Mail settings below are required if gitea mailer is enabled
# 'From:' address used in mails sent by gitea
# gitea_mail_from: "gitea-noreply@{{ gitea_fqdn }}"
# SMTP host, username and password for outgoing mail from gitea
# gitea_mail_host: "{{ vault_gitea_mail_host }}"
# gitea_mail_user: "{{ vault_gitea_mail_user }}"
# gitea_mail_password: "{{ vault_gitea_mail_password }}"
