##### CHECKS FOR SAMBA ROLE #####

- name: check that mandatory variables are correctly defined
  assert:
    that:
      - samba_log_level is string
      - samba_max_log_size_kb == samba_max_log_size_kb|int
      - samba_netbios_name is string
      - samba_server_string is string
      - samba_shares|type_debug == "list"
      - samba_shares_path is string
      - samba_users|type_debug == "list"
      - samba_passdb_backend in ['tdbsam', 'ldapsam']
      - samba_nscd_debug_level == samba_nscd_debug_level|int
      - samba_nscd_cache_time_to_live == samba_nscd_cache_time_to_live|int

- name: check that role requirements are met
  assert:
    that: "'nodiscc.xsrv.openldap' in role_names"
    success_msg: "Role requirements are met."
    fail_msg: "The nodiscc.xsrv.openldap role is required when samba_passdb_backend is 'smbldap'."
  when: samba_passdb_backend == 'ldapsam'
