- include: checks.yml
  tags:
    - samba
    - checks

- include: samba.yml
  become: yes
  tags: samba

- include: samba-ldapsam.yml
  become: yes
  when: samba_passdb_backend == 'ldapsam'
  tags: samba

- include: samba-tdbsam.yml
  become: yes
  when: samba_passdb_backend == 'tdbsam'
  tags: samba

- include: backups.yml
  become: yes
  tags:
    - samba
    - backup

- include: rsyslog.yml
  become: yes
  tags:
    - samba
    - rsyslog
    - monitoring
  when:
    - '"nodiscc.xsrv.monitoring" in role_names'
    - setup_rsyslog|bool

- include: fact.yml
  become: yes
  tags: samba

- include: firewalld.yml
  become: yes
  tags:
    - samba
    - firewall
  when:
    - ansible_local.firewalld.ansible_managed is defined
    - ansible_local.firewalld.ansible_managed|bool

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: samba
