- name: include variable checks tasks
  include: checks.yml
  tags:
    - samba
    - checks

- name: include salba configuration tasks
  include: samba.yml
  become: yes
  tags: samba

- name: include samba ldapsam backend configuration tasks
  include: samba-ldapsam.yml
  become: yes
  when: samba_passdb_backend == 'ldapsam'
  tags: samba

- name: include samba tdbsam backend configuration tasks
  include: samba-tdbsam.yml
  become: yes
  when: samba_passdb_backend == 'tdbsam'
  tags: samba

- name: include rsnapshot/backup configuration tasks
  include: backups.yml
  become: yes
  tags:
    - samba
    - backup
  when:
    - ansible_local.backup.ansible_managed is defined
    - ansible_local.backup.ansible_managed | bool

- name: include rsyslog configuration tasks
  include: rsyslog.yml
  become: yes
  tags:
    - samba
    - rsyslog
    - monitoring
  when:
    - ansible_local.rsyslog.ansible_managed is defined
    - ansible_local.rsyslog.ansible_managed | bool

- name: include firewalld configuration tasks
  include: firewalld.yml
  become: yes
  tags:
    - samba
    - firewall
  when:
    - ansible_local.firewalld.ansible_managed is defined
    - ansible_local.firewalld.ansible_managed | bool

- name: include ansible facts configuration tasks
  include: fact.yml
  become: yes
  tags: samba

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: samba
