- include: checks.yml
  tags:
    - samba
    - checks

- include: samba.yml
  become: yes
  tags: samba

- include: samba-ldapsam.yml
  become: yes
  when: samba_passdb_backend == 'ldapsam'
  tags: samba

- include: samba-tdbsam.yml
  become: yes
  when: samba_passdb_backend == 'tdbsam'
  tags: samba

- include: backups.yml
  become: yes
  tags:
    - samba
    - backup

- include: rsyslog.yml
  become: yes
  tags:
    - samba
    - rsyslog
    - monitoring
  when:
    - '"nodiscc.xsrv.monitoring" in role_names'
    - setup_rsyslog|bool
