# @tag monitoring - setup monitoring/alerting/logging system/utilities
# @tag netdata - setup netdata monitoring system
# @tag rsyslog - setup system log processing
# @tag lynis - setup lynis security audit tool
# @tag monitoring-cli-utils - setup command-line/additional monitoring utilities

galaxy_info:
  role_name: monitoring
  author: "nodiscc <nodiscc@gmail.com>"
  description: "Real-time monitoring, alerting and logging system"
  license: GPL-3.0
  min_ansible_version: 2.8
  platforms:
    - name: Debian
      versions:
        - 9
        - 10
        - 11
  galaxy_tags:
    - system
    - performance
    - monitoring
    - health
    - graph
    - alerts
    - syslog
    - rsyslog
dependencies:
  - nodiscc.xsrv.handlers
