- include: proxmox.yml
  become: yes
  tags: proxmox

- include: fail2ban.yml
  become: yes
  tags:
    - proxmox
    - fail2ban

- include: fact.yml
  become: yes
  tags: proxmox

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: proxmox
