- include: proxmox.yml
  become: yes
  tags: proxmox

- include: fail2ban.yml
  become: yes
  tags:
    - proxmox
    - fail2ban

- include: fact.yml
  become: yes
  tags: proxmox

- include: firewalld.yml
  become: yes
  tags:
    - proxmox
    - firewall
  when:
    - ansible_local.firewalld.ansible_managed is defined
    - ansible_local.firewalld.ansible_managed|bool

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: proxmox
