---

galaxy_info:
  role_name: lamp
  author: "nodiscc <nodiscc@gmail.com>"
  description: "apache web server + mod-php + mysql/mariadb server"
  license: "GPL-3.0"
  min_ansible_version: 2.8
  platforms:
    - name: Debian
      versions:
        - 10
  galaxy_tags:
    - web
    - server
    - apache
    - php
    - mysql
    - mariadb
    - database
    - server
    - lamp

dependencies:
  - common
