- include: checks.yml
  tags:
    - rsnapshot
    - backup

- include: rsnapshot.yml
  become: yes
  tags:
    - rsnapshot
    - backup

- include: monitoring.yml
  become: yes
  tags:
    - rsnapshot
    - backup
    - monitoring
  when:
    - '"nodiscc.xsrv.monitoring" in role_names'
