- include: checks.yml
  tags:
    - rsnapshot
    - backup

- include: rsnapshot.yml
  become: yes
  tags:
    - rsnapshot
    - backup

- include: rsyslog.yml
  become: yes
  tags:
    - rsnapshot
    - backup
    - rsyslog
  when:
    - '"nodiscc.xsrv.monitoring" in role_names'
    - setup_rsyslog|bool
