- include: checks.yml
  tags:
    - backup
    - checks

- include: rsnapshot.yml
  become: yes
  tags: backup

- include: monitoring.yml
  become: yes
  tags:
    - backup
    - monitoring
  when:
    - '"nodiscc.xsrv.monitoring" in role_names'

- include: fact.yml
  become: yes
  tags: backup

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: backup
