- name: configure rsyslog to aggregate rsnapshot logs to syslog
  template:
    src: etc_rsyslog.d_rsnapshot.conf.j2
    dest: /etc/rsyslog.d/rsnapshot.conf
    owner: root
    group: root
    mode: 0644
  notify: restart rsyslog
  when:
    - "'nodiscc.xsrv.monitoring' in role_names"
    - setup_rsyslog|bool
  tags: rsyslog

- name: add netdata modtime check and alarm for rsnapshot
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: netdata
    mode: 0640
  notify: assemble netdata configuration
  with_items:
    - src: etc_netdata_python.d_modtime.conf.d_rsnapshot.conf.j2
      dest: "/etc/netdata/python.d/modtime.conf.d/modtime.conf"
    - src: etc_netdata_health.d_modtime.conf.d_rsnapshot.conf.j2
      dest: "/etc/netdata/health.d/modtime.conf.d/modtime.conf"

- name: ensure rsyslog/netdata configuration is applied (flush handlers)
  meta: flush_handlers
