##### SAMBA FILE SHARING SERVER

# List of samba shares. Each item has the following attributes:
#   name: unique name for the share
#   allow_read_users: list of users allowed to read the share
#   allow_write_users: list of users allowed to write to the share
#   comment: (optional) text string that is seen next to a share in share listings on clients
#   available: (optional, default yes) yes/no: set to no to disable the share
#   browseable: (optional, default yes) yes/no: set to no to hide the share from network share listings on clients (it can still be accessed)
#   state: (optional, default 'directory') directory/absent: set to 'absent' to delete the share. All data will be removed!
# Example:
# samba_shares:
#   - name: mycompany
#     comment: "File share for the whole company"
#     allow_read_users:
#       - alice
#       - bob
#       - martin
#       - eve
#       - boss
#   - name: eve-personal
#     comment: "Eve's personal file storage (hidden from share listing)"
#     browseable: no
#     allow_write_users:
#       - eve
#   - name: accounting
#     comment: "Share for the accounting department"
#     allow_write_users:
#       - martin
#     allow_read_users:
#       - boss
#   - name: old_share
#     state: absent
samba_shares: []

# List of samba_users. Each item has the following attributes:
#   username: the username. Do not use a username already in use by a system service or interactive user!
#   password: password for this user. It is best to store this value in ansible-vault
# Example:
# samba_users:
#   - username: alice
#     password: "{{ vault_samba_user_password_alice }}"
#   - username: bob
#     password: "{{ vault_samba_user_password_bob }}"
samba_users: []

# Server name and description
samba_netbios_name: "{{ ansible_hostname }}"
samba_server_string: "{{ ansible_hostname }} file server"

# Max size of log files (in KiB)
samba_max_log_size_kb: 10000

# Samba log level
samba_log_level: 0

# base path for samba share directories
samba_shares_path: /var/lib/samba/shares/
