##### CHECKS FOR HOMEPAGE ROLE #####

- name: check that mandatory variables are correctly defined
  assert:
    that:
      - homepage_fqdn is not search("CHANGEME")
      - homepage_title is not search("CHANGEME")
      - homepage_https_mode in ['selfsigned', 'letsencrypt']
