- include: checks.yml
  tags:
    - homepage
    - checks

- include: homepage.yml
  become: yes
  tags: homepage

- include: ssl-selfsigned.yml
  become: yes
  tags:
    - apache
    - ssl
    - homepage
  when: homepage_https_mode == 'selfsigned'

- include: apache.yml
  become: yes
  tags:
    - homepage
    - apache

- include: monitoring.yml
  become: yes
  tags:
    - homepage
    - monitoring
  when: "'nodiscc.xsrv.monitoring' in role_names"

- include: fact.yml
  become: yes
  tags: homepage

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: homepage
