---

- name: enable apache2 modules
  command: a2enmod {{ item }}
  with_items:
    - 'rewrite'
    - 'headers'
    - 'env'
    - 'dir'
    - 'mime'
  args:
    creates: "/etc/apache2/mods-enabled/{{ item }}.load"
  notify: reload apache

- name: check that nextcloud_https_mode is one of none/selfsigned/letsencrypt
  assert:
    that: nextcloud_https_mode in ['none', 'selfsigned', 'letsencrypt']
    fail_msg: "Unsupported nextcloud_https_mode: {{ nextcloud_https_mode }}"

- name: copy apache2 virtualhost configuration
  template:
    src: etc_apache2_sites-available_nextcloud.conf.j2
    dest: /etc/apache2/sites-available/nextcloud.conf
  notify: reload apache

- name: enable apache2 virtualhost
  command: a2ensite nextcloud
  args:
    creates: "/etc/apache2/sites-enabled/nextcloud.conf"
  notify: restart apache
