- name: detect php-fpm version
  set_fact:
    php_fpm_version: "{{ item.value }}"
  when: "{{ item.condition }}" # noqa no-jinja-when
  with_items:
    - { value: "7.3", condition: "(ansible_distribution == 'Debian') and (ansible_distribution_release == 'buster')" }
    - { value: "7.4", condition: "(ansible_distribution == 'Debian') and (ansible_distribution_release == 'bullseye')" }

- name: enable apache2 modules
  command: a2enmod {{ item }}
  with_items:
    - 'rewrite'
    - 'headers'
    - 'env'
    - 'dir'
    - 'mime'
  args:
    creates: "/etc/apache2/mods-enabled/{{ item }}.load"
  notify: reload apache

- name: copy php-fpm configuration
  template:
    src: etc_php_PHPVERSION_fpm_pool.d_nextcloud.conf.j2
    dest: /etc/php/{{ php_fpm_version }}/fpm/pool.d/nextcloud.conf
    mode: 0644
  notify: restart php-fpm

- name: copy apache2 virtualhost configuration
  template:
    src: etc_apache2_sites-available_nextcloud.conf.j2
    dest: /etc/apache2/sites-available/nextcloud.conf
    mode: 0644
  notify: reload apache

- name: enable apache2 virtualhost
  command: a2ensite nextcloud
  args:
    creates: "/etc/apache2/sites-enabled/nextcloud.conf"
  notify: restart apache
