### BACKUPS ###

- name: copy rsnapshot configuration for nextcloud backups
  template:
    src: etc_rsnapshot.d_nextcloud.conf.j2
    dest: /etc/rsnapshot.d/nextcloud.conf
    mode: 0600
  when: '"nodiscc.xsrv.backup" in role_names'
  notify: check rsnapshot configuration
