---

##### CHECKS FOR APACHE ROLE #####

- name: check that mandatory variables are correctly defined
  assert:
    that:
      - nextcloud_admin_email is not search("CHANGEME")
      - nextcloud_apps|type_debug == "list"
      - nextcloud_data_dir is string
      - nextcloud_db_host is not search("CHANGEME")
      - nextcloud_db_name is not search("CHANGEME")
      - nextcloud_db_password is not search("CHANGEME")
      - nextcloud_db_table_prefix is string
      - nextcloud_db_type in ['pgsql', 'mysql']
      - nextcloud_db_user is not search("CHANGEME")
      - nextcloud_fqdn is not search("CHANGEME")
      - nextcloud_full_url is not search("CHANGEME")
      - nextcloud_https_mode in ['selfsigned', 'letsencrypt']
      - nextcloud_install_dir is string
      - nextcloud_password is not search("CHANGEME")
      - nextcloud_user is not search("CHANGEME")
      - nextcloud_version is string
