- include: checks.yml
  tags:
    - nextcloud
    - checks

- include: mysql.yml
  become: yes
  tags: nextcloud
  when: nextcloud_db_type == 'mysql'

- include: postgresql.yml
  become: yes
  tags: nextcloud
  when: nextcloud_db_type == 'pgsql'

- include: nextcloud.yml
  become: yes
  tags: nextcloud

- include: ssl-selfsigned.yml
  become: yes
  tags:
    - apache
    - ssl
    - nextcloud
  when: nextcloud_https_mode == 'selfsigned'

- include: apache.yml
  become: yes
  tags:
    - nextcloud
    - apache

- include: backups.yml
  become: yes
  tags:
    - nextcloud
    - backup
  when: "'nodiscc.xsrv.backup' in role_names"

- include: fail2ban.yml
  become: yes
  tags:
    - nextcloud
    - fail2ban
  when:
    - "'nodiscc.xsrv.common' in role_names"
    - setup_fail2ban|bool

- include: monitoring.yml
  become: yes
  tags:
    - nextcloud
    - monitoring
  when: "'nodiscc.xsrv.monitoring' in role_names"

- include: fact.yml
  become: yes
  tags: nextcloud

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: nextcloud
