- name: include variable checks tasks
  include: checks.yml
  tags:
    - nextcloud
    - checks

- name: include mysql configuration tasks
  include: mysql.yml
  become: yes
  tags: nextcloud
  when: nextcloud_db_type == 'mysql'

- name: include postgresql configuration tasks
  include: postgresql.yml
  become: yes
  tags: nextcloud
  when: nextcloud_db_type == 'pgsql'

- name: include nextcloud configuration tasks
  include: nextcloud.yml
  become: yes
  tags: nextcloud

- name: include self-signed certificates configuration tasks
  include: ssl-selfsigned.yml
  become: yes
  tags:
    - apache
    - ssl
    - nextcloud
  when: nextcloud_https_mode == 'selfsigned'

- name: include apache configuration tasks
  include: apache.yml
  become: yes
  tags:
    - nextcloud
    - apache

- name: include rsnapshot/backups configuration tasks
  include: backups.yml
  become: yes
  tags:
    - nextcloud
    - backup
  when:
    - ansible_local.backup.ansible_managed is defined
    - ansible_local.backup.ansible_managed | bool

- name: include fail2ban configuration tasks
  include: fail2ban.yml
  become: yes
  tags:
    - nextcloud
    - fail2ban
  when:
    - ansible_local.fail2ban.ansible_managed is defined
    - ansible_local.fail2ban.ansible_managed | bool

- name: include rsyslog configuration tasks
  include: rsyslog.yml
  become: yes
  tags:
    - nextcloud
    - monitoring
    - rsyslog
  when:
    - ansible_local.rsyslog.ansible_managed is defined
    - ansible_local.rsyslog.ansible_managed | bool

- name: include netdata configuration tasks
  include: netdata.yml
  become: yes
  tags:
    - nextcloud
    - monitoring
    - netdata
  when:
    - ansible_local.netdata.ansible_managed is defined
    - ansible_local.netdata.ansible_managed | bool

- name: include ansible facts configuration tasks
  include: fact.yml
  become: yes
  tags: nextcloud

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: nextcloud
