---

##### PACKAGES #####

- name: install required packages
  apt:
    state: present
    package:
      - php-gmp
      - php-curl
      - php-gd
      - php-imagick
      - php-intl
      - php-json
      - php-ldap
      - php-sqlite3
      - php-mbstring
      - php-xml
      - php-zip
      - php-bz2
      - php-smbclient
      - php-imap
      - php-apcu
      - ffmpeg
      - acl

###### FAIL2BAN ##########

- name: copy nextcloud fail2ban jail config
  template:
    src: etc_fail2ban_jail.d_nextcloud.conf.j2
    dest: /etc/fail2ban/jail.d/nextcloud.conf
    mode: 0600
  tags: fail2ban
  notify: reload fail2ban

- name: copy fail2ban nextcloud-auth filter
  template:
    src: etc_fail2ban_filter.d_nextcloud-auth.conf.j2
    dest: /etc/fail2ban/filter.d/nextcloud-auth.conf
    mode: 0600
  tags: fail2ban
  notify: reload fail2ban

##### BACKUPS #####

- name: copy rsnapshot configuration for nextcloud backups
  template:
    src: etc_rsnapshot.d_nextcloud.conf.j2
    dest: /etc/rsnapshot.d/nextcloud.conf
    mode: 0600
  when: '"backup" in role_names'
  notify: check rsnapshot configuration


##### NEXTCLOUD INSTALLATION #####

- name: check nextcloud if installation directory exists
  stat:
    path: "{{ nextcloud_install_dir }}"
  register: nextcloud_dir

- name: abort on unsupported conditions
  fail:
    msg: "ERROR: unsupported conditions: nextcloud_dir.stat.exists: {{ nextcloud_dir.stat.exists }}, but ansible_local.nextcloud.installed.version says otherwise" # noqa 204
  when: '((ansible_local.nextcloud.installed.version is defined) and (not nextcloud_dir.stat.exists)) or
         ((ansible_local.nextcloud.installed.version is undefined) and (nextcloud_dir.stat.exists))'

- name: check if initial installation should be performed
  set_fact:
    nextcloud_action: initial
  when: '(ansible_local.nextcloud.installed.version is undefined) and (not nextcloud_dir.stat.exists)'

- name: check if upgrade should be performed
  set_fact:
    nextcloud_action: upgrade
  when: '(ansible_local.nextcloud.installed.version is defined) and (ansible_local.nextcloud.installed.version < nextcloud_version) and (nextcloud_dir.stat.exists)' # noqa 204

#- debug:
#    msg: "action: {{ nextcloud_action }}, nextcloud_dir.stat.exists: {{ nextcloud_dir.stat.exists }}, nextcloud_version: {{ nextcloud_version }}"

- name: download nextcloud zip
  get_url:
    url: "https://download.nextcloud.com/server/releases/nextcloud-{{ nextcloud_version }}.zip"
    dest: "/root/nextcloud-{{ nextcloud_version }}.zip"
  when:
    - nextcloud_action is defined
    - nextcloud_action == 'initial' or nextcloud_action == 'upgrade'

- name: remove nextcloud zip extraction directory
  file:
    path: /root/nextcloud-unpack
    state: absent
  when:
    - nextcloud_action is defined
    - nextcloud_action == 'upgrade'

- name: create nextcloud zip extraction directory
  file:
    path: /root/nextcloud-unpack
    state: directory
    mode: 0750
  when:
    - nextcloud_action is defined
    - (nextcloud_action == 'initial') or (nextcloud_action == 'upgrade')

- name: extract nextcloud zip
  unarchive:
    src: "/root/nextcloud-{{ nextcloud_version }}.zip"
    dest: "/root/nextcloud-unpack"
    remote_src: yes
    mode: u=rwX
  when:
    - nextcloud_action is defined
    - (nextcloud_action == 'initial') or (nextcloud_action == 'upgrade')

- name: give write permissions to the webserver
  file:
    path: "{{ item }}"
    group: www-data
    mode: "g+w"
    recurse: no
  with_items:
    - "/root/nextcloud-unpack/nextcloud/apps"
    - "/root/nextcloud-unpack/nextcloud/config"
    - "/root/nextcloud-unpack/nextcloud/themes"
    #- "/root/nextcloud-unpack/nextcloud/updater"
  when:
    - nextcloud_action is defined
    - (nextcloud_action == 'initial') or (nextcloud_action == 'upgrade')

- name: give exexecute permissions to the webserver on occ command-line tool
  file:
    path: "/root/nextcloud-unpack/nextcloud/occ"
    mode: g+X
  when:
    - nextcloud_action is defined
    - (nextcloud_action == 'initial') or (nextcloud_action == 'upgrade')

- name: create/set permissions on nextcloud data directory
  file:
    path: "/var/nextcloud/data"
    state: directory
    owner: root
    group: www-data
    mode: 0770
  when:
    - nextcloud_action is defined
    - (nextcloud_action == 'initial') or (nextcloud_action == 'upgrade')

- name: move old nextcloud installation to temporary dir
  command: mv '{{ nextcloud_install_dir }}' '{{ nextcloud_install_dir }}.old'
  args:
    removes: '{{ nextcloud_install_dir }}'
  when:
    - nextcloud_action is defined
    - nextcloud_action == 'upgrade'

- name: move nextcloud extraction directory to install directory
  command: mv /root/nextcloud-unpack/nextcloud '{{ nextcloud_install_dir }}'
  when:
    - nextcloud_action is defined
    - (nextcloud_action == 'initial') or (nextcloud_action == 'upgrade')

- name: run first setup (this can take a while)
  become: yes
  become_user: www-data
  command: /usr/bin/php occ \
           maintenance:install \
           --database="{{ nextcloud_db_type }}" \
           --database-host="{{ nextcloud_db_host }}" \
           --database-name="{{ nextcloud_db_name }}" \
           --database-table-prefix="{{ nextcloud_db_table_prefix }}" \
           --database-user="{{ nextcloud_db_user }}" \
           --database-pass="{{ nextcloud_db_password }}" \
           --admin-user="{{ nextcloud_user }}" \
           --admin-pass="{{ nextcloud_password }}"
           --data-dir="{{ nextcloud_data_dir }}"
           --admin-email="{{ nextcloud_admin_email }}"
  register: nextcloud_first_setup
  args:
    chdir: "{{ nextcloud_install_dir }}"
  failed_when: nextcloud_first_setup.rc !=0 and 'Command "maintenance:install" is not defined.' not in nextcloud_first_setup.stderr  # noqa 204
  changed_when: nextcloud_first_setup.rc == 0
  when:
    - nextcloud_action is defined
    - nextcloud_action == 'initial'

- name: copy config.php from old installation
  copy:
    remote_src: yes
    src: '{{ nextcloud_install_dir }}.old/config/config.php'
    dest: '{{ nextcloud_install_dir }}/config/config.php'
    owner: www-data
    group: www-data
    mode: 0660
  when:
    - nextcloud_action is defined
    - nextcloud_action == 'upgrade'

# TODO: not idempotent, replace with template-based management of config.php
# TODO: if this fails the install will be left in a broken state, the working copy is still at {{ nextcloud_fqdn }}.old
- name: set nextcloud config.php values (not idempotent, returns changed every time - occ doesn't report changed status)
  become: yes
  become_user: www-data
  command: /usr/bin/php ./occ config:system:set {{ item.key }} --value="{{ item.value }}" # noqa 301
  args:
    chdir: "{{ nextcloud_install_dir }}/"
  with_items:
    - { key: "trusted_domains 1", value: "{{ nextcloud_fqdn }}" }
    - { key: "overwrite.cli.url", value: "{{ nextcloud_full_url }}" }
    - { key: "datadir", value: "{{ nextcloud_data_dir }}" }
    - { key: "dbtype", value: "{{ nextcloud_db_type }}" }
    - { key: "dbname", value: "{{ nextcloud_db_name }}" }
    - { key: "dbhost", value: "{{ nextcloud_db_host }}" }
    - { key: "dbtableprefix", value: "{{ nextcloud_db_table_prefix }}" }
    - { key: "dbuser", value: "{{ nextcloud_db_user }}" }
    - { key: "dbpassword", value: "{{ nextcloud_db_password }}" }
    - { key: "logtimezone", value: "UTC" }
    - { key: "log_type", value: "syslog" }
    - { key: "log_authfailip", value: "true" }
    - { key: "loglevel", value: "2" }
    - { key: "trashbin_retention_obligation", value: "auto" }
    - { key: "memcache.local", value: '\OC\Memcache\APCu' }
  no_log: True
  tags: nextcloud_config_php

# trashbin_retention_obligation:
#   auto: keep for 30 days, then delete IF space needed
#   D, auto: keep at least D+ days, then delete IF space needed
#   auto, D: max D days, but delete if space needed
#   D1, D2: keep lat east D1 days and max D2 days
#   disabled: auto clean disabled

- name: run nextcloud upgrade command
  become: True
  become_user: www-data
  command: /usr/bin/php ./occ upgrade
  args:
    chdir: "{{ nextcloud_install_dir }}"
  register: nextcloud_upgrade
  changed_when: not 'Nextcloud is already at the latest version' in nextcloud_upgrade.stdout
  when:
    - nextcloud_action is defined
    - (nextcloud_action == 'initial') or (nextcloud_action == 'upgrade')

- name: create ansible facts.d directory
  file:
    path: /etc/ansible/facts.d
    state: directory
    mode: 0755

- name: create nextcloud installed fact file
  template:
    src: etc_ansible_facts.d_nextcloud.fact.j2
    dest: /etc/ansible/facts.d/nextcloud.fact
    mode: 0644

###### NEXTCLOUD APPLICATIONS ######

- name: install nextcloud applications
  become: yes
  become_user: www-data
  command: /usr/bin/php ./occ app:install {{ item.app }}
  args:
    chdir: "{{ nextcloud_install_dir }}"
  with_items: "{{ nextcloud_apps }}"
  register: nextcloud_app_install
  when:
    - 'item.state == "enable"'
  changed_when:
    - not 'already installed' in nextcloud_app_install.stdout
  failed_when:
    - nextcloud_app_install.rc !=0 and not 'not compatible with this version of the server' not in nextcloud_app_install.stderr

- name: enable/disable nextcloud applications
  become: yes
  become_user: www-data
  command: /usr/bin/php ./occ app:{{ item.state }} {{ item.app }}
  args:
    chdir: "{{ nextcloud_install_dir }}"
  with_items: "{{ nextcloud_apps }}"
  register: nextcloud_app_enable_disable
  changed_when:
    - not 'No such app enabled' in nextcloud_app_enable_disable.stdout
    - not 'already enabled' in nextcloud_app_enable_disable.stdout

- name: update nextcloud applications (not imdepotent, always upgrade to latest version) # noqa 301
  become: yes
  become_user: www-data
  command: /usr/bin/php ./occ app:update --all
  args:
    chdir: "{{ nextcloud_install_dir }}"

##### CLEANUP #####

- name: remove old nextcloud installation
  file:
    path: '{{ nextcloud_install_dir }}.old'
    state: absent
  when:
    - nextcloud_action is defined
    - nextcloud_action == 'upgrade'
