- name: install interactive/command-line monitoring tools
  apt:
    state: present
    package:
      - ncdu # ncurses disk usage viewer
      - nethogs # network bandwidth usage monitor
      - htop # system monitor/process manager
      - lsof # list open files
      - strace # trace system calls
      - lnav # enhanced log file viewer
