- include: checks.yml
  tags:
    - monitoring
    - netdata
    - rsyslog
    - checks

- include: rsyslog.yml
  become: yes
  tags:
    - monitoring
    - rsyslog
  when: setup_rsyslog|bool

- include: netdata.yml
  become: yes
  tags:
    - monitoring
    - netdata

- include: netdata-module-needrestart.yml
  become: yes
  tags:
    - monitoring
    - netdata
  when: setup_needrestart|bool

- include: netdata-module-logcount.yml
  become: yes
  tags:
    - monitoring
    - netdata
  when: setup_netdata_logcount|bool

- include: netdata-module-debsecan.yml
  become: yes
  tags:
    - monitoring
    - netdata
  when: setup_netdata_debsecan|bool

- include: firewalld.yml
  become: yes
  tags:
    - monitoring
    - netdata
    - firewall
  when:
    - ansible_local.firewalld.ansible_managed is defined
    - ansible_local.firewalld.ansible_managed|bool

- include: cli-utils.yml
  become: yes
  tags:
    - monitoring
    - monitoring-cli-utils
  when: setup_monitoring_cli_utils|bool

- include: lynis.yml
  become: yes
  tags:
    - monitoring
    - lynis
  when: setup_lynis|bool

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags:
    - monitoring
    - rsyslog
    - netdata
    - firewall
