---

- include: checks.yml
  tags:
    - monitoring

- include: rsyslog.yml
  become: yes
  tags:
    - monitoring
    - rsyslog
    - syslog
  when: setup_rsyslog|bool

- include: netdata.yml
  become: yes
  tags:
    - monitoring
    - netdata

- include: netdata-modules.yml
  become: yes
  tags:
    - monitoring
    - netdata

- include: cli-utils.yml
  become: yes
  tags:
    - monitoring
    - monitoring-utils
  when: setup_monitoring_cli_utils|bool
