---

##### CHECKS FOR APACHE ROLE #####

- name: check that mandatory variables are correctly defined
  assert:
    that:
      - tt_rss_account_limit == tt_rss_account_limit|int
      - tt_rss_allow_registration in ['true', 'false']
      - tt_rss_db_host is not search("CHANGEME")
      - tt_rss_db_name is not search("CHANGEME")
      - tt_rss_db_password is not search("CHANGEME")
      - tt_rss_db_port == tt_rss_db_port|int
      - tt_rss_db_type in ['mysql', 'pgsql']
      - tt_rss_db_user is not search("CHANGEME")
      - tt_rss_fqdn is not search("CHANGEME")
      - tt_rss_full_url is not search("CHANGEME")
      - tt_rss_https_mode in ['selfsigned', 'letsencrypt']
      - tt_rss_install_dir is not search("CHANGEME")
      - tt_rss_install_plugins == tt_rss_install_plugins|bool
      - tt_rss_install_themes == tt_rss_install_themes|bool
      - tt_rss_log_destination is string
      - tt_rss_password is not search("CHANGEME")
      - tt_rss_password_salt|length == 250
      - tt_rss_user is not search("CHANGEME")
      - tt_rss_version is string
