- include: checks.yml
  tags:
    - tt_rss
    - checks

- include: postgresql.yml
  become: yes
  tags: tt_rss

- include: tt-rss.yml
  become: yes
  tags: tt_rss

- include: ssl-selfsigned.yml
  become: yes
  tags: tt_rss
  when: tt_rss_https_mode == 'selfsigned'

- include: apache.yml
  become: yes
  tags: tt_rss

- include: themes.yml
  become: yes
  tags: tt_rss
  when: tt_rss_install_themes|bool

- include: plugins.yml
  become: yes
  tags: tt_rss
  when: tt_rss_install_plugins|bool

- include: monitoring.yml
  become: yes
  tags:
    - tt_rss
    - monitoring
  when: "'nodiscc.xsrv.monitoring' in role_names"

- include: fact.yml
  become: yes
  tags: tt_rss

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: tt_rss
