---

- include: checks.yml
  tags:
    - tt-rss

- include: postgresql.yml
  become: yes
  tags:
    - tt-rss

- include: tt-rss.yml
  become: yes
  tags:
    - tt-rss

- include: ssl-selfsigned.yml
  become: yes
  tags:
    - tt-rss
  when: tt_rss_https_mode == 'selfsigned'

- include: apache.yml
  become: yes
  tags:
    - tt-rss

- include: themes.yml
  become: yes
  tags:
    - tt-rss
    - tt-rss-themes
  when: tt_rss_install_themes|bool

- include: plugins.yml
  become: yes
  tags:
    - tt-rss
    - tt-rss-plugins
  when: tt_rss_install_plugins|bool
