- name: add netdata httpcheck for tt-rss
  template:
    src: etc_netdata_go.d_httpcheck.conf.d_tt-rss.conf.j2
    dest: "/etc/netdata/go.d/httpcheck.conf.d/tt-rss.conf"
    owner: root
    group: netdata
    mode: 0640
  notify: assemble netdata configuration

- name: ensure netdata configuration is applied (flush handlers)
  meta: flush_handlers
