- include: checks.yml
  tags:
    - mariadb
    - lamp
    - checks

- include: mariadb.yml
  become: yes
  tags:
    - mariadb
    - lamp

- include: monitoring.yml
  become: yes
  tags:
    - mariadb
    - lamp
    - monitoring
  when: "'nodiscc.xsrv.monitoring' in role_names"
