##### CHECKS FOR TRANSMISSION ROLE #####

- name: check that mandatory variables are correctly defined
  assert:
    that:
      - transmission_download_dir is not search("CHANGEME")
      - transmission_enable_service == transmission_enable_service|bool
      - transmission_fqdn is not search("CHANGEME")
      - transmission_https_mode is in ["selfsigned", "letsencrypt"]
      - transmission_password is not search("CHANGEME")
      - transmission_port == transmission_port|int
      - transmission_username is not search("CHANGEME")
