- name: check that required variables/roles are correctly defined/enabled
  assert:
    quiet: yes
    that:
      - transmission_download_dir is string
      - transmission_enable_service == transmission_enable_service|bool
      - transmission_fqdn is not search("CHANGEME")
      - transmission_https_mode is in ["selfsigned", "letsencrypt"]
      - transmission_password is not search("CHANGEME")
      - transmission_username is not search("CHANGEME")
      - transmission_backup_downloads == transmission_backup_downloads|bool
      - transmission_firewalld_zones|type_debug == "list"
