- include: checks.yml
  tags: transmission

- include: transmission.yml
  become: yes
  tags: transmission

- include: ssl-selfsigned.yml
  become: yes
  tags: transmission
  when: transmission_https_mode == 'selfsigned'

- include: apache.yml
  become: yes
  tags: transmission

- name: restart services to apply configuration changes
  meta: flush_handlers
  tags: transmission
