- include: checks.yml
  tags:
    - transmission
    - checks

- include: transmission.yml
  become: yes
  tags: transmission

- include: ssl-selfsigned.yml
  become: yes
  tags: transmission
  when: transmission_https_mode == 'selfsigned'

- include: apache.yml
  become: yes
  tags:
    - transmission
    - apache

- include: monitoring.yml
  become: yes
  tags:
    - transmission
    - monitoring
  when: "'nodiscc.xsrv.monitoring' in role_names"

- include: fact.yml
  become: yes
  tags: transmission

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: transmission
