##### PACKAGES #####

- name: install transmission
  apt:
    package: transmission-daemon
    state: present

##### CONFIGURATION #####

- name: copy transmission-daemon configuration
  template:
    src: "etc_transmission-daemon_settings.json.j2"
    dest: "/etc/transmission-daemon/settings.json"
    owner: debian-transmission
    group: debian-transmission
    mode: 0600
  notify: reload transmission-daemon
  no_log: True

- name: add ansible user to debian-transmission group
  user:
    name: "{{ ansible_user }}"
    groups: debian-transmission
    append: yes

- name: create symlink to download directory in main users home
  file:
    state: link
    src: "{{ transmission_download_dir }}"
    dest: "/home/{{ ansible_user }}/TORRENTS"

##### SERVICE #####

- name: start/stop/enable/disable transmission-daemon service
  service:
    name: transmission-daemon
    state: "{{ 'started' if transmission_enable_service else 'stopped' }}"
    enabled: "{{ 'yes' if transmission_enable_service else 'no' }}"
  tags: services
