##### SHAARLI - APACHE CONFIGURATION #####

- name: enable apache2 modules
  command: a2enmod {{ item }}
  with_items:
    - ssl
    - rewrite
  args:
    creates: "/etc/apache2/mods-enabled/{{ item }}.load"
  notify: reload apache

- name: copy php-fpm configuration
  template:
    src: etc_php_7.3_fpm_pool.d_shaarli.conf.j2
    dest: /etc/php/7.3/fpm/pool.d/shaarli.conf
    mode: 0644
  notify: restart php-fpm

- name: copy apache2 virtualhost configuration
  template:
    src: etc_apache2_sites-available_shaarli.conf.j2
    dest: /etc/apache2/sites-available/shaarli.conf
    mode: 0644
  notify: reload apache

- name: enable apache2 virtualhost
  command: a2ensite shaarli
  args:
    creates: "/etc/apache2/sites-enabled/shaarli.conf"
  notify: reload apache
