##### CHECKS FOR SHAARLI ROLE #####

- name: check that mandatory variables are correctly defined
  assert:
    that:
      - shaarli_api_secret|length >= 12
      - shaarli_fqdn is not search("CHANGEME")
      - shaarli_https_mode is in ["selfsigned", "letsencrypt"]
      - shaarli_install_dir is string
      - shaarli_overwrite_config == shaarli_overwrite_config|bool
      - shaarli_password is not search("CHANGEME")
      - shaarli_password_salt is not search("CHANGEME")
      - shaarli_timezone is string
      - shaarli_username is not search("CHANGEME")
      - shaarli_version is string
      - shaarli_php_memory_limit|regex_search('[KMG]$')
      - shaarli_php_max_execution_time == shaarli_php_max_execution_time|int
      - shaarli_php_max_input_time == shaarli_php_max_input_time|int
      - shaarli_php_post_max_size|regex_search('[KMG]$')
      - shaarli_php_upload_max_filesize|regex_search('[KMG]$')
