- include: checks.yml
  tags: shaarli

- include: shaarli.yml
  become: yes
  tags: shaarli

- include: ssl-selfsigned.yml
  become: yes
  tags: shaarli
  when: shaarli_https_mode == 'selfsigned'

- include: apache.yml
  become: yes
  tags: shaarli

- include: monitoring.yml
  become: yes
  tags:
    - shaarli
    - monitoring
  when: "'nodiscc.xsrv.monitoring' in role_names"
