- name: include variable checks tasks
  include: checks.yml
  tags:
    - shaarli
    - checks

- name: include shaarli configuration tasks
  include: shaarli.yml
  become: yes
  tags: shaarli

- name: include self-signed certificates configuration tasks
  include: ssl-selfsigned.yml
  become: yes
  tags:
    - apache
    - ssl
    - shaarli
  when: shaarli_https_mode == 'selfsigned'

- name: include apache configuration tasks
  include: apache.yml
  become: yes
  tags:
    - shaarli
    - apache

- name: include rsnapshot/backup configuration tasks
  include: backups.yml
  become: yes
  tags:
    - shaarli
    - backup
  when:
    - ansible_local.backup.ansible_managed is defined
    - ansible_local.backup.ansible_managed | bool

- name: include fail2ban configuration tasks
  include: fail2ban.yml
  become: yes
  tags:
    - shaarli
    - fail2ban
  when:
    - ansible_local.fail2ban.ansible_managed is defined
    - ansible_local.fail2ban.ansible_managed | bool

- name: include rsyslog configuration tasks
  include: rsyslog.yml
  become: yes
  tags:
    - shaarli
    - monitoring
    - rsyslog
  when:
    - ansible_local.rsyslog.ansible_managed is defined
    - ansible_local.rsyslog.ansible_managed | bool

- name: include netdata configuration tasks
  include: netdata.yml
  become: yes
  tags:
    - shaarli
    - monitoring
    - netdata
  when:
    - ansible_local.netdata.ansible_managed is defined
    - ansible_local.netdata.ansible_managed | bool

- name: include ansible facts configuration tasks
  include: fact.yml
  become: yes
  tags: shaarli

- name: include python-shaarli-client configuration tasks
  include: shaarli-client.yml
  become: yes
  tags:
    - shaarli
    - shaarli-client
  when: shaarli_setup_python_client|bool

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: shaarli
