- include: checks.yml
  tags:
    - shaarli
    - checks

- include: shaarli.yml
  become: yes
  tags: shaarli

- include: ssl-selfsigned.yml
  become: yes
  tags:
    - apache
    - ssl
    - shaarli
  when: shaarli_https_mode == 'selfsigned'

- include: apache.yml
  become: yes
  tags:
    - shaarli
    - apache

- include: monitoring.yml
  become: yes
  tags:
    - shaarli
    - monitoring
  when: "'nodiscc.xsrv.monitoring' in role_names"

- include: fact.yml
  become: yes
  tags: shaarli

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: shaarli
