- name: check that mandatory variables are correctly defined
  assert:
    quiet: yes
    that:
      - rsyslog_enable_forwarding == rsyslog_enable_forwarding|bool

- name: check that mandatory variables are correctly defined (syslog forwarding)
  assert:
    quiet: yes
    that:
      - rsyslog_forward_to_hostname is not search('CHANGEME')
      - rsyslog_forward_to_port == rsyslog_forward_to_port|int
  when: rsyslog_enable_forwarding
