- name: include variable checks tasks
  include: checks.yml
  tags:
    - monitoring
    - rsyslog
    - checks

- name: include rsyslog configuration tasks
  include: rsyslog.yml
  become: yes
  tags:
    - monitoring
    - rsyslog

- name: include ansibel facts configuration tasks
  include: fact.yml
  become: yes
  tags:
    - monitoring
    - rsyslog

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags:
    - monitoring
    - rsyslog
