galaxy_info:
  role_name: nextcloud
  author: "nodiscc <nodiscc@gmail.com>"
  description: "file hosting/sharing/synchronization service and collaboration platform"
  license: GPL-3.0
  min_ansible_version: 2.8
  platforms:
    - name: Debian
      versions:
        - 9
        - 10
  galaxy_tags:
    - server
    - groupware
    - calendar
    - synchronization
    - dropbox
    - addressbook
    - contacts
    - tasks
    - sharing
    - agenda
    - caldav
    - carddav
    - webdav
    - drive
    - web
dependencies:
  # - nodiscc.xsrv.common # optional
  # - nodiscc.xsrv.backup # optional
  # - nodiscc.xsrv.monitoring # optional
  - nodiscc.xsrv.apache
  - { role: 'nodiscc.xsrv.postgresql', when: nextcloud_db_type == "pgsql" }
  - { role: 'nodiscc.xsrv.mariadb', when: nextcloud_db_type == "mysql" }
