galaxy_info:
  role_name: nextcloud
  author: "nodiscc <nodiscc@gmail.com>"
  description: "file hosting/sharing/synchronization and collaboration platform"
  license: GPL-3.0
  min_ansible_version: 2.8
  platforms:
    - name: Debian
      versions:
        - 11
  galaxy_tags:
    - server
    - groupware
    - calendar
    - synchronization
    - dropbox
    - addressbook
    - contacts
    - tasks
    - sharing
    - agenda
    - caldav
    - carddav
    - webdav
    - drive
    - web
dependencies:
  - nodiscc.xsrv.handlers
  # - nodiscc.xsrv.common
  # - nodiscc.xsrv.backup
  # - nodiscc.xsrv.monitoring
  - nodiscc.xsrv.apache
  - { role: 'nodiscc.xsrv.postgresql', when: nextcloud_db_type == "pgsql" }
