---

##### SERVICE CONTROL

- name: apply sysctl configuration
  become: yes
  command: sysctl --load /etc/sysctl.d/custom.conf

- name: update apt cache
  become: yes
  apt: update_cache=yes

- name: update pam configuration
  become: yes
  command: 'pam-auth-update --package'

- name: restart ssh
  become: yes
  service: name=ssh state=restarted enabled=yes

- name: reload systemd unit files
  become: yes
  systemd: daemon_reload=yes

- name: reload fail2ban
  become: yes
  service: name=fail2ban state=reloaded enabled=yes

- name: restart firewall
  become: yes
  service: name=firehol state=restarted enabled=yes
