- name: apply sysctl configuration
  become: yes
  command: sysctl --load /etc/sysctl.d/custom.con

- name: update pam configuration
  become: yes
  command: 'pam-auth-update --package'

- name: restart ssh
  become: yes
  service:
    name: ssh
    state: restarted
    enabled: yes
