# @tag openldap - setup LDAP server
# @tag ldap-account-manager - setup LDAP account manager
# @tag self-service-password - setup LDAP self-service password

galaxy_info:
  role_name: openldap
  author: "nodiscc <nodiscc@gmail.com>"
  description: "LDAP directory server"
  license: "GPL-3.0"
  min_ansible_version: 2.7
  platforms:
    - name: Debian
      versions:
        - buster
  galaxy_tags:
    - ldap
    - directory
    - authentication
dependencies:
  - nodiscc.xsrv.handlers
  - nodiscc.xsrv.common
  # - nodiscc.xsrv.monitoring
  # - nodiscc.xsrv.backup
  - { role: nodiscc.xsrv.apache, when: (openldap_setup_lam|bool) or (openldap_setup_ssp|bool) }
