- include: checks.yml
  tags:
    - jitsi
    - checks

- include: jitsi.yml
  become: yes
  tags: jitsi

- include: jitsi-users.yml
  become: yes
  tags:
    - jitsi
    - jitsi-users

- include: fail2ban.yml
  become: yes
  tags:
    - jitsi
    - fail2ban
  when:
    - ansible_local.fail2ban.ansible_managed is defined
    - ansible_local.fail2ban.ansible_managed | bool

- include: rsyslog.yml
  become: yes
  tags:
    - jitsi
    - monitoring
    - rsyslog
  when:
    - ansible_local.rsyslog.ansible_managed is defined
    - ansible_local.rsyslog.ansible_managed | bool

- include: fact.yml
  become: yes
  tags: jitsi

- include: firewalld.yml
  become: yes
  tags:
    - jitsi
    - firewall
  when:
    - ansible_local.firewalld.ansible_managed is defined
    - ansible_local.firewalld.ansible_managed | bool

- include: ssl-selfsigned.yml
  become: yes
  tags:
    - jitsi
    - ssl

- include: apache.yml
  become: yes
  tags:
    - jitsi
    - firewall
  when:
    - ansible_local.apache.ansible_managed is defined
    - ansible_local.apache.ansible_managed | bool

- include: netdata.yml
  become: yes
  tags:
    - jitsi
    - monitoring
    - netdata
  when:
    - ansible_local.netdata.ansible_managed is defined
    - ansible_local.netdata.ansible_managed | bool

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags:
    - jitsi
    - monitoring
    - fail2ban
