##### CHECKS FOR ROCKETCHAT ROLE #####

- name: check that mandatory variables are correctly defined
  assert:
    that:
      - rocketchat_docker_version is string
      - rocketchat_fqdn is not search("CHANGEME")
      - nextcloud_https_mode in ['selfsigned', 'letsencrypt']
