- name: check that mandatory variables are correctly defined
  assert:
    quiet: yes
    that:
      - rocketchat_docker_version is string
      - rocketchat_fqdn is not search("CHANGEME")
      - rocketchat_https_mode in ['selfsigned', 'letsencrypt']
      - rocketchat_enable_service == rocketchat_enable_service|bool
