- include: checks.yml
  tags:
    - rocketchat
    - checks

- include: rocketchat.yml
  become: yes
  tags: rocketchat

- include: ssl-selfsigned.yml
  become: yes
  tags: rocketchat
  when: rocketchat_https_mode == 'selfsigned'

- include: apache.yml
  become: yes
  tags:
    - rocketchat
    - apache

- include: monitoring.yml
  become: yes
  tags:
    - rocketchat
    - monitoring
  when: "'nodiscc.xsrv.monitoring' in role_names"
