galaxy_info:
  role_name: graylog
  author: "nodiscc <nodiscc@gmail.com>"
  description: "Log capture, storage, real-time search and analysis tool"
  license: "GPL-3.0"
  min_ansible_version: 2.10
  platforms:
    - name: Debian
      versions:
        - 10
  galaxy_tags:
    - logs
    - logging
    - monitoring
    - aggregator
    - syslog
    - analyzer
    - siem
dependencies:
  # - nodiscc.xsrv.monitoring # optional
  - nodiscc.xsrv.apache
