---

##### APACHE SSL/TLS CERTIFICATES - SELF-SIGNED #####

# We add a self-signed certificate for the domain 'localhost', and use it for the default
# virtualhost (served for requests that do not match any configured servername)
# It prevents disclosing the CN for the first 'real' virtualhost certificate, when accessing the server directly by IP address

- name: generate openssl private keys
  openssl_privatekey:
    path: "/etc/ssl/private/{{ item.servername }}.key"
  when: item.cert_mode == 'selfsigned'
  with_items: "{{ apache_virtualhosts + [ {'servername': 'localhost', 'cert_mode': 'selfsigned'} ] }}"
  notify: restart apache

- name: generate openssl certficate signing requests
  openssl_csr:
    path: "/etc/ssl/private/{{ item.servername }}.csr"
    privatekey_path: "/etc/ssl/private/{{ item.servername }}.key"
    common_name: "{{ item.servername }}"
  when: item.cert_mode == 'selfsigned'
  with_items: "{{ apache_virtualhosts + [ {'servername': 'localhost', 'cert_mode': 'selfsigned'} ] }}"

- name: generate self-signed openssl certificates
  openssl_certificate:
    path: "/etc/ssl/certs/{{ item.servername }}.crt"
    privatekey_path: "/etc/ssl/private/{{ item.servername }}.key"
    csr_path: "/etc/ssl/private/{{ item.servername }}.csr"
    provider: selfsigned
  when: item.cert_mode == 'selfsigned'
  with_items: "{{ apache_virtualhosts + [ {'servername': 'localhost', 'cert_mode': 'selfsigned'} ] }}"
  notify: restart apache
