---

- name: create homepage resources directory
  file:
    path: "/opt/xsrv/homepage/res/"
    state: directory
    owner: root
    group: www-data
    mode: 0750

- name: install homepage resources
  copy:
    src: "homepage/res/{{ item }}"
    dest: "/opt/xsrv/homepage/res/{{ item }}"
    owner: root
    group: www-data
    mode: 0640
  with_items:
    - gitea.png
    - icecast.png
    - nextcloud.png
    - services.png
    - shaarli.png
    - transmission.png
    - tt-rss.png
    - netdata.png
    - folder.png
    - terminal.png

- name: create symlinks to resource directory in documentroots
  file:
    src: /opt/xsrv/homepage/res
    dest: "{{ item.documentroot }}/res"
    owner: root
    group: www-data
    mode: 0750
    state: link
  with_items: "{{ apache_virtualhosts }}"
  when:
    - item.auto_homepage is defined
    - item.auto_homepage

- name: update virtualhost homepage
  template:
    src: homepage/index.html.j2
    dest: "{{ item.documentroot }}/index.html"
    owner: root
    group: www-data
    mode: 0640
  with_items: "{{ apache_virtualhosts }}"
  when:
    - item.auto_homepage is defined
    - item.auto_homepage
