---

- include: apache-ssl-selfsigned.yml
  become: yes
  tags:
    - apache
    - lamp
    - certificates
    - ssl

- include: apache.yml
  become: yes
  tags:
    - apache
    - lamp

- include: mariadb.yml
  become: yes
  tags:
    - mariadb
    - lamp

- name: restart apache to apply configuration changes
  meta: flush_handlers
