- name: copy apt sources lists (debian + security + backports)
  template:
    src: "etc_apt_sources.list.j2"
    dest: "/etc/apt/sources.list"
    mode: 0644
  when: ansible_facts.distribution == 'Debian'
  notify: update apt cache

- name: copy apt config (automatic upgrades, no recommended packages, don't overwrite conffiles)
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items:
    - { src: 'etc_apt_apt.conf.d_99no-overwrite-conffiles.j2', dest: '/etc/apt/apt.conf.d/99no-overwrite-conffiles' }
    - { src: 'etc_apt_apt.conf.d_99norecommends.j2', dest: '/etc/apt/apt.conf.d/99norecommends' }
    - { src: 'etc_apt_apt.conf.d_50unattended-upgrades.j2', dest: '/etc/apt/apt.conf.d/50unattended-upgrades' }
  when: ansible_facts.distribution == 'Debian'

- name: remove files from old versions of the role
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/apt/apt.conf.d/99-norecommends
    - /etc/apt/apt.conf.d/99-no-overwrite-conffiles

# update apt cache
- name: apply configuration (flush handlers)
  meta: flush_handlers

- name: install unattended-upgrades
  apt:
    state: present
    package:
      - unattended-upgrades
      - apt-listchanges
