##### DATE/TIME #####

- name: set timezone
  community.general.timezone:
    name: "{{ timezone }}"
  when: timezone is defined

- name: install NTP time synchronization service
  apt:
    state: present
    package:
      - ntp
      - ntpdate
