- name: check if host is already running the target distribution
  debug:
    msg: "Host is already running Debian 11. Nothing to do."
  when: ansible_distribution_release == "bullseye"

- name: upgrade Debian 10 to 11
  when: ansible_distribution_release == "buster"
  block:
    - name: upgrade all packages to latest Debian 10 versions
      apt:
        upgrade: safe
        autoremove: yes
        purge: yes
        update_cache: yes
    - name: list APT sources configuration files
      find:
        path: /etc/apt/sources.list.d/
        patterns: '*.list'
      register: apt_sources_files
    - name: replace buster with bullseye in APT sources list
      replace:
        path: "{{ item }}"
        regexp: "buster"
        replace: "bullseye"
      with_items: "{{ apt_sources_files.files | map(attribute='path') | list + ['/etc/apt/sources.list'] }}"
    - name: update Debian security APT source URL for Debian 11
      replace:
        path: "{{ item }}"
        regexp: "deb https?://security.debian.org/debian-security bullseye/updates"
        replace: "deb https://security.debian.org/debian-security bullseye-security"
      with_items: "{{ apt_sources_files.files | map(attribute='path') | list + ['/etc/apt/sources.list'] }}"
    - name: upgrade all packages to Debian 11 versions
      apt:
        upgrade: dist
        update_cache: yes
        autoremove: yes
        purge: yes
    - name: reboot host
      reboot:
        reboot_timeout: 6000
    - name: show upgrade completion message
      debug:
        msg: "Upgrade to Debian 11 complete. Please run the playbook against this host to apply up-to-date configuration for Debian 11."
