---

##### OUTGOING SYSTEM MAIL #####

- name: ensure outgoing email credentials/host has been set
  assert:
    that:
      - not msmtp_host == "smtp.example.com"
      - not msmtp_username == "CHANGEME"
      - not msmtp_password == "CHANGEME"
    fail_msg: "Please set configuration variables msmtp_host/username/password or disable msmtp installation"

- name: copy msmtp configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: "etc_msmtprc.j2", dest: "/etc/msmtprc" }
    - { src: "etc_aliases.j2", dest: "/etc/aliases" }

- name: install msmtp SMTP client as system MTA
  apt:
    package:
      - msmtp
      - msmtp-mta
    state: present
    update_cache: true
    cache_valid_time: 900
