##### APACHE WEB SERVER #####
# yes/no: listen on port 80 (unencrypted HTTP)
apache_listen_http: yes
# yes/no: ask search engines/bots that respect the X-Robots-Tag header not to crawl this webserver's sites
apache_allow_robots: no
# yes/no: start/stop the apache webserver, enable/disable it on boot
apache_enable_service: yes
# yes/no: enable mod_evasive for basic DoS protection (can interfere with legitimate traffic)
apache_enable_mod_evasive: no
# e-mail address to register a letsencrypt.org account
apache_letsencrypt_email: "CHANGEME"

##### PHP-FPM INTERPRETER #####
# yes/no: enable/disable the default php-fpm pool (www)
# starting php-fpm without any pool defined will cause the service to fail
php_fpm_enable_default_pool: yes
