- name: include variable checks tasks
  include: checks.yml
  tags:
    - dovecot
    - mail
    - checks

- name: include self-signed certificates configuration tasks
  include: ssl-selfsigned.yml
  become: yes
  tags:
    - dovecot
    - mail
    - ssl

- name: include dovecot configuration tasks
  include: dovecot.yml
  become: yes
  tags:
    - dovecot
    - mail

- name: include fail2ban configuration tasks
  include: fail2ban.yml
  become: yes
  tags:
    - dovecot
    - mail
    - fail2ban
  when:
    - ansible_local.fail2ban.ansible_managed is defined
    - ansible_local.fail2ban.ansible_managed | bool

- name: include firewalld configuration tasks
  include: firewalld.yml
  become: yes
  tags:
    - dovecot
    - mail
    - firewall
  when:
    - ansible_local.firewalld.ansible_managed is defined
    - ansible_local.firewalld.ansible_managed | bool

- name: include rsnapshot/backup configuration tasks
  include: backups.yml
  become: yes
  tags:
    - gitea
    - backup
  when:
    - ansible_local.backup.ansible_managed is defined
    - ansible_local.backup.ansible_managed | bool

- name: include netdata configuration tasks
  include: netdata.yml
  become: yes
  tags:
    - dovecot
    - mail
    - monitoring
    - netdata
  when:
    - ansible_local.netdata.ansible_managed is defined
    - ansible_local.netdata.ansible_managed | bool

- name: include ansibel facts configuration tasks
  include: fact.yml
  become: yes
  tags: dovecot

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: dovecot
