- name: include variable checks tasks
  include: checks.yml
  tags:
    - graylog
    - checks

- name: include graylog requirements configuration tasks
  include: requirements.yml
  become: yes
  tags: graylog

- name: include mongodb configuration tasks
  include: mongodb.yml
  become: yes
  tags: graylog

- name: include elasticsearch configuration tasks
  include: elasticsearch.yml
  become: yes
  tags: graylog

- name: include graylog configuration tasks
  include: graylog.yml
  become: yes
  tags: graylog

- name: include self-signed certificates configuration tasks
  include: ssl-selfsigned.yml
  become: yes
  tags:
    - apache
    - ssl
    - graylog
  when: graylog_https_mode == 'selfsigned'

- name: include apache configuration tasks
  include: apache.yml
  become: yes
  tags:
    - graylog
    - apache

- name: include rsyslog configuration tasks
  include: rsyslog.yml
  become: yes
  tags:
    - graylog
    - monitoring
    - rsyslog
  when:
    - ansible_local.rsyslog.ansible_managed is defined
    - ansible_local.rsyslog.ansible_managed | bool

- name: include netdata configuration tasks
  include: netdata.yml
  become: yes
  tags:
    - graylog
    - monitoring
    - netdata
  when:
    - ansible_local.netdata.ansible_managed is defined
    - ansible_local.netdata.ansible_managed | bool

- name: include ansible facts configuration tasks
  include: fact.yml
  become: yes
  tags: graylog

- name: include firewalld configuration tasks
  include: firewalld.yml
  become: yes
  tags:
    - graylog
    - firewall
  when:
    - ansible_local.firewalld.ansible_managed is defined
    - ansible_local.firewalld.ansible_managed | bool

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: graylog
