### GRAYLOG REQUIREMENTS ###

- name: install graylog requirements
  apt:
    state: present
    package:
      - default-jre
      - apt-transport-https
      - uuid-runtime
      - pwgen
      - dirmngr
      - gnupg
      - wget
      - python3-openssl
      - ssl-cert