- name: include variable checks tasks
  include: checks.yml
  tags:
    - dnsmasq
    - checks

- name: include dnsmasq configuration tasks
  include: dnsmasq.yml
  become: yes
  tags: dnsmasq

- name: include firewalld configuration tasks
  include: firewalld.yml
  become: yes
  tags:
    - dnsmasq
    - firewall
  when:
    - ansible_local.firewalld.ansible_managed is defined
    - ansible_local.firewalld.ansible_managed | bool

- name: include ansible facts configuration tasks
  include: fact.yml
  become: yes
  tags: backup

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: dnsmasq
