##### CHECKS FOR MUMBLE ROLE #####

- name: check that mandatory variables are correctly defined
  assert:
    that:
      - mumble_superuser_password is not search("CHANGEME")
      - mumble_superuser_password is not search(" ")
      - mumble_password is not search("CHANGEME")
      - mumble_welcome_text is string
