- name: include variable checks tasks
  include: checks.yml
  become: yes
  tags:
    - mumble
    - checks

- name: include mumble configuration tasks
  include: mumble.yml
  become: yes
  tags: mumble

- name: include fail2ban configuration tasks
  include: fail2ban.yml
  become: yes
  tags:
    - mumble
    - fail2ban
  when:
    - ansible_local.fail2ban.ansible_managed is defined
    - ansible_local.fail2ban.ansible_managed | bool

- name: include rsnapshot/backup configuration tasks
  include: backups.yml
  become: yes
  tags:
    - mumble
    - backup
  when:
    - ansible_local.backup.ansible_managed is defined
    - ansible_local.backup.ansible_managed | bool

- name: include rsyslog configuration tasks
  include: rsyslog.yml
  become: yes
  tags:
    - mumble
    - monitoring
    - rsyslog
  when:
    - ansible_local.rsyslog.ansible_managed is defined
    - ansible_local.rsyslog.ansible_managed | bool

- name: include netdata configuration tasks
  include: netdata.yml
  become: yes
  tags:
    - mumble
    - monitoring
    - netdata
  when:
    - ansible_local.netdata.ansible_managed is defined
    - ansible_local.netdata.ansible_managed | bool

- name: include firewalld configuration tasks
  include: firewalld.yml
  become: yes
  tags:
    - mumble
    - firewall
  when:
    - ansible_local.firewalld.ansible_managed is defined
    - ansible_local.firewalld.ansible_managed | bool

- name: include ansible facts configuration tasks
  include: fact.yml
  become: yes
  tags: mumble

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: mumble
