- include: checks.yml
  become: yes
  tags: mumble

- include: mumble.yml
  become: yes
  tags: mumble

- include: monitoring.yml
  become: yes
  tags:
    - mumble
    - monitoring
  when:
    - '"nodiscc.xsrv.monitoring" in role_names'
