- include: mumble.yml
  become: yes
  tags: mumble

- include: rsyslog.yml
  become: yes
  tags:
    - mumble
    - rsyslog
  when:
    - '"nodiscc.xsrv.monitoring" in role_names'
    - setup_rsyslog|bool
