- include: checks.yml
  become: yes
  tags:
    - mumble
    - checks

- include: mumble.yml
  become: yes
  tags: mumble

- include: monitoring.yml
  become: yes
  tags:
    - mumble
    - monitoring
  when: '"nodiscc.xsrv.monitoring" in role_names'

- include: fact.yml
  become: yes
  tags: mumble

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: mumble
