- name: install netdata process check for mumble
  template:
    src: etc_netdata_health.d_processes.conf.d_mumble.conf.j2
    dest: /etc/netdata/health.d/processes.conf.d/mumble.conf
    owner: root
    group: netdata
    mode: 0640
  notify: assemble netdata configuration
