- name: include docker configuration tasks
  include: docker.yml
  become: yes
  tags: docker

- name: include netdata configuration tasks
  include: netdata.yml
  become: yes
  tags:
    - docker
    - monitoring
    - netdata
  when:
    - ansible_local.netdata.ansible_managed is defined
    - ansible_local.netdata.ansible_managed | bool

- name: include firewalld configuration tasks
  include: firewalld.yml
  become: yes
  tags:
    - docker
    - firewall
  when:
    - ansible_local.firewalld.ansible_managed is defined
    - ansible_local.firewalld.ansible_managed | bool

- name: include ansibeln facts configuration tasks
  include: fact.yml
  become: yes
  tags: docker

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: docker
