##### SERVICE CONTROL #####

# roles that need to install their own imfile/other rsyslog configuration should create a file
# '/etc/rsyslog.d/COMPONENT_NAME.conf' and notify the 'restart rsyslog' handler
- name: restart rsyslog
  become: yes
  service:
    name: rsyslog
    state: restarted
    enabled: yes

- name: restart netdata
  become: yes
  service:
    name: netdata
    state: restarted
    enabled: yes
  when: not ansible_check_mode

- name: re-execute the systemd manager
  become: yes
  systemd:
    daemon_reexec: yes
