- name: restart rsyslog
  become: yes
  service:
    name: rsyslog
    state: restarted
    enabled: yes

- name: assemble netdata configuration
  become: yes
  assemble:
    src: /etc/netdata/{{ item }}.d
    dest: /etc/netdata/{{ item }}
    owner: root
    group: netdata
    mode: 0640
  with_items:
    - go.d/httpcheck.conf
    - go.d/x509check.conf
    - go.d/portcheck.conf
    - python.d/modtime.conf
    - health.d/modtime.conf
    - health.d/processes.conf
  notify: restart netdata
  ignore_errors: "{{ ansible_check_mode }}"

- name: restart netdata
  become: yes
  service:
    name: netdata
    state: restarted
    enabled: yes
  ignore_errors: "{{ ansible_check_mode }}"

- name: re-execute the systemd manager
  become: yes
  systemd:
    daemon_reexec: yes

- name: update apt cache
  become: yes
  apt:
    update_cache: yes

- name: update ansible facts
  setup:
