- name: include monitoring-utils configuration tasks
  include: monitoring-utils.yml
  become: yes
  tags:
    - monitoring
    - monitoring_utils

- name: include lynis configuration tasks
  include: lynis.yml
  become: yes
  tags:
    - monitoring
    - monitoring_utils
    - lynis

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags:
    - monitoring
    - monitoring_utils
    - lynis
